### ISSUE TITLE
How does one defer execution?

### ISSUE THREAD

**Issue by rostero1** [zeit/swr#10]
Is there an option to defer execution?  For example, what if I want only want to fetch the resource (and make the network request) when the user clicks on "fetch"?

**Comment by pacocoursey** [comment]
Yes! The first parameter to `useSWR` is a key, but this key can be a function. If the function throws or returns a falsy value, then SWR will know that not everything is ready to begin the fetching yet.

> fetch the resource when the user clicks

Here's an example of how that could look:

```jsx
const FetchingButton = () => {
  const [startFetch, setStartFetch] = useState(false)
  const { data } = useSWR(
    () => startFetch ? '/api/projects' : null
  )

  return '<button onClick={() => setStartFetch(true)}>Fetch!</button>'
}
```

You can see another example of this, but with data dependencies, here:

https://swr.now.sh/#dependent-fetching

**Comment by aequasi** [comment]
I think it would be very beneficial to provide this as an export :)

**Comment by pacocoursey** [comment]
> I want this refetch in some scenarios, but not in others

You can control this somewhat using the `dedupingInterval` configuration option (e.g. `dedupingInterval: 5000` means if there are multiple requests to the same key within 5 seconds, only one will be made).

Hopefully that satisfies your use case, let me know if not!

**Comment by rostero1** [comment]
Thanks, that would solve the problem for my use case.  I just wasn't sure why it was happening.  For example, why does reselecting the simpsons refetch the simpsons characters in the dropdown, but not in the "Simpsons Characters" box, which doesn't get rerendered during this time.

**Comment by pacocoursey** [comment]
In your example, SWR refetches in both cases (selecting a different value in the dropdown, and clicking revalidate in the sidebar box). The difference is that in the dropdown, you return early when the data is validating in the background, so you never show the stale data (even when it's available).

If you're asking why the sidebar box doesn't update with new data when the dropdown revalidates, it's because you're using different SWR keys so they don't share a cache! In the dropdown you use `/api/user` and in the sidebar box you use `the-simpsons`.

**Comment by rostero1** [comment]
Thanks.  I thought `isValidating` would run for all components that are wired with the same swr `key`.  Sorry for the confusion.

I simplified the example:  https://codesandbox.io/s/elated-pare-m9wdn

**Comment by pacocoursey** [comment]
> Thanks. I thought isValidating would run for all components that are wired with the same swr key. 

Good point, maybe we can clarify this in the documentation.

> close the issue

Sounds good! Let me know if you have any other questions or issues.
