### ISSUE TITLE
Support Non-String Keys

### ISSUE THREAD

**Issue by bhurlow** [zeit/swr#103]
It would be useful for my usage of SWR to allow for non-string keys. I'm using database ids as keys which appear to be coerced to strings. 

I would also like to use arrays/tuples as keys. For example: `['context', 12123908]` to add differentiation. I presume this would require some kind of deeper equality check for cache invalidation etc.

Thoughts? Thanks!

**Comment by quietshu** [comment]
We're going to support it soon, check #98 :)

**Comment by bhurlow** [comment]
awesome thanks! checked for duplicates but missed that one
