### ISSUE TITLE
Why key not support object ? 

### ISSUE THREAD

**Issue by beidan** [zeit/swr#112]
![image](https://user-images.githubusercontent.com/17068068/68658547-9c00de00-0570-11ea-9e63-42cf869b858c.png)
i want to call function like this that can make it more customized. 
![image](https://user-images.githubusercontent.com/17068068/68658597-b6d35280-0570-11ea-8927-3ca2080f8ace.png)
![image](https://user-images.githubusercontent.com/17068068/68658673-d9fe0200-0570-11ea-91a6-0285139620f0.png)

**Comment by quietshu** [comment]
Please read this: https://github.com/zeit/swr#multiple-arguments

Also don't pass `{ ... }` (you need to memorize it). In your case, it should be just an array:

```js
useSWR(['something', schoolCode], callAPI)
```
