### ISSUE TITLE
Multiple Arguments lead to Infinite loop

### ISSUE THREAD

**Issue by beidan** [zeit/swr#113]
in my code,  when i pass one param it can success. 
but when i pass Multiple Arguments , it Infinite loop. 
![image](https://user-images.githubusercontent.com/17068068/68667854-f2c2e380-0581-11ea-8cee-c4e869856541.png)
![image](https://user-images.githubusercontent.com/17068068/68667887-feaea580-0581-11ea-9002-c9e61486669f.png)

**Comment by quietshu** [comment]
> SWR shallowly compares the arguments on every render, and triggers the validation if any of them has changed.

Like I said here https://github.com/zeit/swr/issues/112#issuecomment-552809810, don't pass `{ schoolCode }` as an argument because `{} !== {}`. It works exactly like React Hook dependencies.

You can do either:

```js
useSWR(['...', useMemo(() => ({ schoolCode }), [schoolCode])], fetcher)
```

or

```js
useSWR(['...', schoolCode], (method, schoolCode) => fetcher(method, { schoolCode }))
```

**Comment by beidan** [comment]
maybe It's better to write it in a document
![image](https://user-images.githubusercontent.com/17068068/68668598-88ab3e00-0583-11ea-9d8e-5419af9eb760.png)

thanks ~
