### ISSUE TITLE
Rerender multiple times 

### ISSUE THREAD

**Issue by beidan** [zeit/swr#114]
when i use swr, i find it will rerender multiple times.

maybe **useSWR** use many **useState** ……
![image](https://user-images.githubusercontent.com/17068068/68670120-19374d80-0587-11ea-8320-4b3a45e688be.png)

but my application doesnot need so many states.
Will it affect performance? 
When not in use, whether  can remove **useState** or Stop updating the state ?

**Comment by pacocoursey** [comment]
Yes, components using SWR will re-render multiple times to update the return values (data, error, isValidating).

Currently there is no way to avoid this, if you don't need all these extra options maybe SWR isn't best suited for your use case. May I ask what your use case is?

**Comment by quietshu** [comment]
> maybe useSWR use many useState

It won’t cause multiple re-renders because it’s using batched updates. FYI: https://stackoverflow.com/questions/48563650/does-react-keep-the-order-for-state-updates/48610973#48610973

**Comment by beidan** [comment]
There may be many requests for a page. But not every request requires loading . 
Can the loading state be customized ?

**Comment by quietshu** [comment]
@beidan if you read this: https://github.com/zeit/swr/blob/master/src/use-swr.ts#L242-L263

Data, error and validating states are batched, there will be **only 1** re-render. Although we will change those `useState` to `useReducer` in the future, but that will not cause any difference. Maybe you see the re-rendering because of the revalidation.

> But not every request requires loading.

I think it's a basic requirement for a data-fetching library, to have the loading state, error state and the data.

**Comment by beidan** [comment]
> @beidan if you read this: https://github.com/zeit/swr/blob/master/src/use-swr.ts#L242-L263
> 
> Data, error and validating states are batched, there will be **only 1** re-render. Although we will change those `useState` to `useReducer` in the future, but that will not cause any difference. Maybe you see the re-rendering because of the revalidation.
> 
> > But not every request requires loading.
> 
> I think it's a basic requirement for a data-fetching library, to have the loading state, error state and the data.

thanks ~ perfect

**Comment by quietshu** [comment]
@beidan let me know if there's any other question! We're also going to ship #117 soon.
