### ISSUE TITLE
Suspense mode 

### ISSUE THREAD

**Issue by beidan** [zeit/swr#119]
hi~ I came again.

Suspense mode is not recommended by react officially yet. 
Is it not used in the production environment for the time being?

**Comment by Kexin-Li** [comment]
Yep, Suspense is an experimental feature, only available in the experimental build. you can install an experimental build by run this command:
```
npm install react@experimental react-dom@experimental
```

See more: https://reactjs.org/docs/concurrent-mode-adoption.html

**Comment by sergiodxa** [comment]
Concurrent Mode is experimental, but Suspense it's not, you could use it already for Code Splitting with React.lazy and SWR works with that Suspense version too.
