### ISSUE TITLE
Fetcher obtains data, but data and error are undefined

### ISSUE THREAD

**Issue by jasonlor** [zeit/swr#122]
Love the simplicity of this library. I’m having some trouble in the handoff of the data from the fetcher to useSWR. 

My setup
- Typescript
- NextJS
- Fetcher - GraphQL Client (fetch.ts)
```
require("fetch-cookie/node-fetch")(require("node-fetch"))
export default async function(query, variables, token) {
  const data = await graphql.request(query, variables)
  console.log("fetch.ts ", data)
  return data
}

```
- SWRConfig

```

<SWRConfig value={{ fetcher: (query, variables, token) => fetch(query, variables, token) }}>

<SWRConfig value={{ fetcher: (query, variables, token) => fetch(query, variables, token).then(res => console.log(res)) }}>

```

Both setups return valid data. 

- useSWR

```

const { data, error } = useSWR<DataQueryType>([GraphQLQuery, props, token])

```

Data and error remains undefined despite the fetch response being successful on the server and fetch client. 

Refreshing the page doesn’t appear to help either. It seems like the useSWR isn’t passing the result to the data object. 

Happy to gather additional logs/details.

**Comment by jasonlor** [comment]
Just found #71. Will try and report back. In my case, I’m not using state but haven’t directly specified a type for the return data. 

Might be a useful note to add to the docs.

**Comment by quietshu** [comment]
Can you share an demo (maybe a codesandbox link) so I can reproduce? Thanks! 🙏

**Comment by ivan-kleshnin** [comment]
@jasonlor how are you going to use this library with NextJS if the latter relies on `static getInitialProps` (an entirely different approach to data fetching)?

**Comment by pacocoursey** [comment]
@ivan-kleshnin Next.js provides `getInitialProps` but does not require you to use it (with Next.js 9, pages are automatically optimized between SSR and Static Prerendering).

`useSWR` is very compatible with Next.js, all of [the examples](https://github.com/zeit/swr/tree/master/examples) use it!

**Comment by ivan-kleshnin** [comment]
@pacocoursey I mean people use NextJS mostly to get SSR. useSWR library does not support SSR at the moment. So NextJS + useSWR combination makes little sense to me.

**Comment by quietshu** [comment]
@ivan-kleshnin SWR is mostly for client side data updates. For example a dashboard or any web apps with changing data. 

That said, even if it is server side rendered, you’ll still have to tackle that problem. That’s why we have been using Next.js and SWR on zeit.co for more than 6 months.

Currently the community seems not to have a clear solution on Suspense especially with preloading, SSR, etc. and it’s still an experimental feature. But you can still use the getInitialProps way and here’s an example:

```js
App.getInitialProps = async getInitialProps () {
  const data = await fetcher('/api/data')
  return { data }
}

function App (props) {
  const initialData = props.data
  const { data } = useSWR('/api/data', fetcher, { initialData })
  // note there’s this `initialData` option available

  return <div>{data}</div>
}
```

In this example, everything works the same just like a normal SSR Next.js app. But it’s also fully powered by SWR in the client side, which means the data can be dynamic now. 

Sorry for not mentioning it in the documentation — we want to explore all the possibilities carefully and make sure it really works, before adding it as a new feature.

**Comment by jasonlor** [comment]
First time putting something into code sandbox. I hope this is right.
https://codesandbox.io/s/admiring-sun-8s0vy?fontsize=14&hidenavigation=1&theme=dark

**SWRComponent, URQLComponent**
I setup two components, one using SWR and one with URQL.
Both are pointed to the same graphql endpoint. For SWR, graphql-request lives in fetch.ts.

By default, the SWRComponent is disabled due to this error:
`A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.`

I have a console log outputting under App() that indicates that this might be from SWR.
`console.log(fetch(query).then(res => Promise.resolve(res)));`

This code, poorly typed, should illustrate and perhaps indicate the problem.
1.  Fetch-client successfully returns data.
2. SWR has an error, potentially due CORS.

I hope this helps.

**Comment by quietshu** [comment]
Hi @jasonlor! I forked your sandbox and fixed the issue: https://codesandbox.io/s/beautiful-thunder-7lylp

There're 2 problems, one is that you shouldn't pass `{}` to useSWR's args:
```js
useSWR([query, {}, "bleh"])
```
Because SWR shallowly compares those args, just like the deps array in `useEffect` (explained here: https://github.com/zeit/swr#multiple-arguments).

And the other one is the extra `.data` here:
```js
{data.data.country.name}
```

Hope that helps!

**Comment by quietshu** [comment]
Let me know if you have other questions  🙏
