### ISSUE TITLE
`useSWRPages`: How to access the other pages from inside `pageFn`?

### ISSUE THREAD

**Issue by Ephys** [zeit/swr#124]
Hello :)

I'm trying to render paginated content, but I cannot figure out how to properly access other pages when rendering a given page. I need to do that because how I'm going to render one of the item in my page depends on what item is after & before it (for context: a chat in which conversation bubbles have a smaller margin if the next bubble is from the same sender)

My current solution was to access `pagesResponseInterface` from the return value of `useSWRPages` like this:

```javascript
function usePagedMessages(param) {

  const pageResponseRef = React.useRef();

  const pagesResponse = useSWRPages(
    'demo-paged-messages',
    ({ offset, withSWR }) => {
      const swr = withSWR(
		// wrapper around useSwr
        useMessages(param, offset),
      );

      /* render swr using pageResponse to determine what item is before/after the first&last items of swr */
      return render(swr, pageResponseRef.current);
    },
    ({ data }) => {
      return data.pageInfo.next;
    },
    [param],
  );

  pageResponseRef.current = pageResponse;

  return pagesResponse;
}
```

(I did it through a ref because using `pagesResponse` directly didn't give an up-to-date `pageSWRs` array.)

My current issue is that in `pageFn`, the swr inside of `pagesResponse` is not 100% up-to-date, so I'm trying to replace it with the `swr` object but I have no way of identifying which page that is. This is especially important for optimistic updates.

The quick fix for me would be to expose `key` inside of `swr` so I can identify them and replace them.

I'm pretty sure this is not how I'm supposed to do this so an official way to do this is also quite welcome :)

Thank you very much for your help

**Comment by quietshu** [comment]
Hi @Ephys ! There's a simple trick to do things like this, you can use the `pageSWRs` value:

```js
function App() {
  const { pages, pageSWRs, ... } = useSWRPages(
    'pages',
    ({ offset, withSWR }) => {
      withSWR(
        useData(offset)
      );

      // don't render anything
      return null;
    },
    ({ data }) => {
      return data.pageInfo.next;
    },
    [],
  );

  // you can get all SWRs' data here
  const data = pageSWRs.map(swr => swr.data);

  // always render `pages` even if it's null
  return <div>
    {pages}
    { /* render data here */}
  </div>
}
```

You can use `page` as a component just for loading SWR hooks dynamically :)

**Comment by Ephys** [comment]
Hi @quietshu, thanks for the quick response!

I didn't do it this way because I assumed rendering from inside `pageFn` was important but I now realize it isn't as long as useData is in it :)

This is definitely a big help! Thank you :)
