### ISSUE TITLE
Allow disabling/overriding deep equality check

### ISSUE THREAD

**Issue by pelotom** [zeit/swr#147]
I spent several hours banging my head against a problem where my fetch function was being called and producing new data, but `useSWR` was still returning the old data. I believe I've figured out that the problem is this line:

https://github.com/zeit/swr/blob/ace1b26bd3dc32066f26bc13665b88a0562b8ed2/src/use-swr.ts#L286-L288

which can produce false positives when your data is not simple and JSON-ish. Our existing API functions that I'm trying to make this work with return values which are class instances, and `fast-deep-equals` isn't able to correctly determine whether 2 instances are equal.

Besides this problem, it seems like a deep equality check, no matter how "fast" it may be, is always going to be expensive relative to a simple reference equality check, and therefore should maybe be opt-in? If not opt-in, then at least it should be possible to opt out of deep equality checks. Whether opt-in or opt-out, the option to provide a custom comparator to override `fast-deep-equals` would be cool!

**Comment by pelotom** [comment]
The more I think about it, the more I like that result deduping is part of the library, I just really need it to be customizable!

**Comment by quietshu** [comment]
Great suggestion, thank you @pelotom! I think it's necessary to add support for the custom comparison option. 👍 `fast-deep-equals` doesn't support circular JSON too.

**Comment by joshkel** [comment]
Since #219 was merged, I think this can be closed.
