### ISSUE TITLE
revalidateOnFocus error

### ISSUE THREAD

**Issue by Airwavess** [zeit/swr#153]
RevalidateOnFocus will not work in some cases.

https://codesandbox.io/s/revalidateonfocus-error-z10ud?fontsize=14&hidenavigation=1&theme=dark

**Comment by quietshu** [comment]
I see what you mean. The "click" and "focus" events happen at the same time, which causes some race condition, and the correct one was overridden  👍

**Comment by Airwavess** [comment]
Revalidate also will not work in mutate. After I mutate the local data, swr doesn't refetch the remote data again.
https://codesandbox.io/s/local-mutate-b0fpc

**Comment by quietshu** [comment]
@Airwavess that's because of deduping and the focus and mutate events happened too quickly so the revalidation got ignored. If you set `dedupingInterval: 0` then it will be fine.

This is also something we're going to fix too, thanks for letting us know.

**Comment by quietshu** [comment]
@Airwavess I just released the fix in v0.1.13. It should work now.
