### ISSUE TITLE
[Question] Exception vs null for Dependent fetching

### ISSUE THREAD

**Issue by Svish** [zeit/swr#154]
Probably obvious, but I'd just like to be sure as I'm trying to create a domain specific wrapper of `useSWR` for us to use in our project.

The readme gives the following example about dependent fetching:

```js
function MyProjects () {
  const { data: user } = useSWR('/api/user')
  const { data: projects } = useSWR(() => '/api/projects?uid=' + user.id)

  if (!projects) return 'loading...'
  return 'You have ' + projects.length + ' projects'
}
```

For dependent fetching, it says that "If the function throws, SWR will know that some dependencies are not ready."

For _conditional_ fetching, it says that "If the functions throws an error _or returns a falsy value_, SWR will cancel the request." Does that mean that the above example could also have been the following?

```js
function MyProjects () {
  const { data: user } = useSWR('/api/user')
  const { data: projects } = useSWR(user && '/api/projects?uid=' + user.id)

  if (!projects) return 'loading...'
  return 'You have ' + projects.length + ' projects'
}
```

Would that give the exact same result, or does `useSWR` do anything extra/different/special in the "key is function that throws" case that it does not do in the case of "key is null" or "key is function that returns null"?

**Comment by quietshu** [comment]
Yeah, they're exactly the same. The "dependent fetching function" is just a trick so you don't have to check the dependencies manually : )

**Comment by Svish** [comment]
Cool! Thanks for quick reply! 😁
