### ISSUE TITLE
Return data from mutate

### ISSUE THREAD

**Issue by sergiodxa** [zeit/swr#155]
Now that `mutate` support passing an async function to get the data it will be helpful to get that data as return value of `mutate`.

```js
const data = await mutate('/api/data', fetch('/api/data').then(res => res.json()))
// use data
```

This way if I want to use the data right now for something else I don't need to use the old way of first fetch and await and then pass the data to `mutate` and return it below.

```js
const data = await fetch('/api/data').then(res => res.json());
mutate('/api/data', data)
// use data
```

**Comment by quietshu** [comment]
Good suggestion 👍 That was what we wanted to do too.
And I think it would be great to do this together with #136 in v0.2 to have a more general, unified API. We will probably merge `revalidate` and `mutate` (maybe it needs to be renamed):

```js
const { mutate } = useSWR(...)

// it supports:

mutate() // revalidate
mutate(newData) // update data
mutate(newData, true) // update data + revalidate
mutate(post()) // update data from a promise
mutate(post(), true) // update data from a promise + revalidate
mutate(key => post()) // update data from an async function
mutate(key => post(), true) // update data from an async function + revalidate
const res = await mutate(...) // return the data
```

Same for the global `import { mutate } from 'swr'`, it accepts a key as the first parameter and everything else will stay the same.

**Comment by BrunoQuaresma** [comment]
I think would be nice to have this interface as well:
```
mutate(key, data => { ...data, [newId]: newData })
```

**Comment by juhaelee** [comment]
> I think would be nice to have this interface as well:
> 
> ```js
> mutate(key, data => { ...data, [newId]: newData })
> ```

would this new API allow us to essentially mutate an endpoint that was fetched from an adjacent component? for example:

`<TodoList A />` :
```
const {data: todos} = useSWR('key1')

const addTodo = (todo) => {
   mutate('key1', [...todos, todo]);
   mutate('key2', (todoListBtodos) => [...todoListBTodos, todo]);
}
```

`<TodoList B /> `:
```
const {data: todos} = useSWR('key2');
```

**Comment by sergiodxa** [comment]
Yeah, you should be able to mutate any key used in your app even if you don’t have the current data in the scope of your mutate call.

**Comment by bflemi3** [comment]
> Yeah, you should be able to mutate any key used in your app even if you don’t have the current data in the scope of your mutate call.

What if the key doesn't exist yet? Will the key be created in the cache upon mutation, or is the data argument (second argument) ignored?

```
import { mutate } from 'swr'

const MyComponent = () => {
  const onChange = (value) => {
    mutate(
      'non/existent/key', 
      () => fetch('non/existent/key', { method: 'PUT', body: value })
    )
  }

  return (
    <div>...</div>
  )
}
```
