### ISSUE TITLE
Fetching for each data in collection

### ISSUE THREAD

**Issue by fa10** [zeit/swr#156]
When you have a dependent call and you want to make a call for each of the data in the collection, how does you handle that with swr? 

```
  const { data: users } = useSWR<Response<User[]>>(
    [usersURL(), token],
    request,
    { revalidateOnFocus: false },
  );

  const allProfiles = [];
  if (users) {
    users .data.forEach(user => {
      const { data: profiles } = useSWR<Response<Profile[]>>(
        [userProfileURL(user.id), token],
        request,
        { revalidateOnFocus: false },
      );

      if (profiles) {
        allProfiles.push(profiles);
      }
    });
  }
```

The above code snippet does not work, I am getting errors like this **Rendered fewer hooks than expected**.

**Comment by sergiodxa** [comment]
I think the best way to solve this is to move each individual fetch to the
component where it's being rendered, so you will do something like:

```js
function Profile({ id }) {
  const { data: profile } = useSWR([userProfileURL(user.id), token], request, {
    revalidateOnFocus: false
  });

  if (!profile) return <h1>Loading...</h1>;

  return <h1>{profile.fullName}</h1>;
}

function Users() {
  const { data: users } = useSWR([usersURL(), token], request, {
    revalidateOnFocus: false
  });

  return users.map(user => <Profile {...user} key={user.id} />);
}
```

**Comment by fa10** [comment]
Thanks for the response!
This does not solve it, when you need all the data in the same component for example graphing and etc.

**Comment by sergiodxa** [comment]
In that case you need your backend to support that use case, if you are not using GraphQL you may need either to follow the JSON:API spec (or something similar) and have a way to include related data in the response (e.g. with JSON:API you would do `/api/profiles?include=users` something like that) or you will need a custom endpoint to get that data at the same time.

Another alternative is to pass a `fetcher` function which send all the request and gives you the full composed data. Remember the first argument of `useSWR` is not really the URL, but a cache key and arguments for your `fetcher`, so you don't need to match it with the final URL neither the `fetcher` should do a single request.

**Comment by fa10** [comment]
@sergiodxa this is the solution I went for!
```javascript
const fetchSomething = async (id: string, token: string) => {
  try {
    const { data: collection } = await request(
      `${id}/data`,
      token,
    );

    const responses = await Promise.all(
      collection.map(site =>
        request(/data, token),
      ),
    );

    return { data: flatten(responses .map(response => response.data)) };
  } catch (error) {
    return { data: undefined, error };
  }
};
````
Then use the `fetchSomething` like this:
```javascript
  const { data } = useSWR(
    [id, token],
    fetchSomething,
  );
```

**Comment by pacocoursey** [comment]
Looks like this has been solved!

For future reference, the error 

> Rendered fewer hooks than expected.

Is caused by using hooks under a conditional:

```js
if (users) {
  // ...
  useSWR(...) // breaks the rules of react hooks
}
```

Additionally, you can do dependent fetching as described here: https://github.com/zeit/swr#dependent-fetching
