### ISSUE TITLE
Any way to communicate request progress to swr?

### ISSUE THREAD

**Issue by Ephys** [zeit/swr#159]
Hello :)

Is there any plans to let us pass the progression percentage of the current fetch operation to `useSWR`?

Maybe something like

```
useSWR(
	'/big-dataset',
	(emitProgress) => /* fetch & call emitProgress when new data is loaded */,
	{ trackProgress: true },
);
```

This would allow us to use determinate progress indicators :)

Thanks!

**Comment by quietshu** [comment]
Why not handling that inside fetcher?  😄

```js
const [progress, emitProgress] = useState(0)
useSWR('/big-dataset', url => fetch(url, emitProgress))
```

Or you can build your own abstraction around that (like a custom hook `useSWRWithProgress`).

I think one of the most important feature of SWR is keep it tiny but highly flexible (isolated from the actual fetch handler).

Related to #129.

**Comment by Ephys** [comment]
That solution works for me, thanks :)

**Comment by Gregoirevda** [comment]
The issue with the proposition is that `progress` is scoped to the hook:
```js
function useSWRProgress() {
  const [progress, emitProgress] = useState(0)
  const response = useSWR('/big-dataset', url => fetch(url, emitProgress))
  return {progress, ...response}
}
```

Using the hook in several places (or prefetch) will sync `isLoading, isValidated, data, ...` but progress will not.
The solution is to add a `ProgressProvider` which keep similar state to swr `{[path]: progress}` so the progress is globally shared, but this seems like a features which should be part of swr.
