### ISSUE TITLE
[Bug] Unexpected result when fetcher returns `false`

### ISSUE THREAD

**Issue by AngusFu** [zeit/swr#164]
## Description

Always suspending  when the fetcher returns (strictly, "resolved with") `false`.

![image](https://user-images.githubusercontent.com/8180186/69900630-d9f36400-13b0-11ea-927c-8a180910dbcf.png)

```jsx
async function fetcher() {
  return false;
}

async function fetcher2() {
  return true;
}

function Demo() {
  const { data: ok } = useSWR("/api", fetcher, { suspense: true });
  return <h1>{ok ? "Ok" : "Not ok"}</h1>;
}

function Demo2() {
  const { data: ok } = useSWR("/api2", fetcher2, { suspense: true });
  return <h1>{ok ? "Ok" : "Not ok"}</h1>;
}

<>
    <Suspense fallback={<h1>loading...</h1>}>
    <Demo />
    </Suspense>
    <Suspense fallback={<h1>loading...</h1>}>
    <Demo2 />
    </Suspense>
</>

```

## Way to reproduce

See the codesandbox demo:

https://codesandbox.io/s/loving-grass-pv9ey

**Comment by AngusFu** [comment]
PS: Seems all falsy values in JavaScript (`""  false 0`) would get the above result, which is unexpected.

**Comment by quietshu** [comment]
Thanks for reporting! Will get this fixed soon.
