### ISSUE TITLE
Fetcher gets called much more than I expect

### ISSUE THREAD

**Issue by Haroenv** [zeit/swr#167]
There seems to be some kind of setInterval or similar which seems to refetch the data, even if it didn't change, which would mean I need to implement a kind of cache myself?

Example app is here https://codesandbox.io/s/vibrant-hamilton-dzgt4

It seems to refetch if you're off the page and reactivate it, but also sometimes just on schedule, or when the component rerenders for another reason

Hope to figure out if I maybe misunderstood it?

**Comment by Haroenv** [comment]
<img width="514" alt="Screenshot 2019-12-02 at 17 31 15" src="https://user-images.githubusercontent.com/6270048/69976915-17c7c800-152a-11ea-9e74-c54f187d518d.png">

here you see in the console that the fetcher was called with the same arguments multiple times

**Comment by quietshu** [comment]
Hi @Haroenv unfortunately I can't reproduce. It's only being called when I refocus on the page (or the preview panel in codesandbox since it's an iframe). 

You can disable revalidation on focus by using `useSWR(key, fetcher, { revalidateOnFocus: false })` and see if it still refetches.

**Comment by Haroenv** [comment]
I didn't see that there were options there, revalidating there indeed doesn't make sense for my use case. Is there API docs somewhere I missed?

**Comment by sergiodxa** [comment]
@Haroenv you can see all the options here https://github.com/zeit/swr#options
`revalidateOnFocus` is enabled by default, the rest of revalidations are disabled by default, except retry on error.

**Comment by Haroenv** [comment]
That clarifies it, thanks!

**Comment by OmarZeidan** [comment]
Well, making `revalidateOnFocus` false doesn't really make anysense in the following scenario

I am "on the page" and "focusing" I clicked another Link (takes me to another route/page) it refetch the data .. why? 

I think `revalidateOnFocus` should revalidate on focus and as described, but not when clicking on another route/link!

@sergiodxa

**Comment by sergiodxa** [comment]
Was your component remounted somehow? SWR revalidate any useSWR call when it’s mounted, even if data was in cache, to ensure it’s not stale.

**Comment by OmarZeidan** [comment]
Thanks for your reply @sergiodxa 

Well, its not. I am moving from a page to another (I am using `nextjs` for sure)

**Comment by sergiodxa** [comment]
If your call to useSWR is not inside _app.js it will be remounted after a page change if I’m not wrong. You could try it, add a useEffect that runs a console.log and it has an empty dependency array, if the component is remounted it will not be logged more than once, if it’s logged again your component remounted.

**Comment by OmarZeidan** [comment]
Nop, its being logged only once .. when I get back to the page itself but not when I leave to another page.
