### ISSUE TITLE
Example about pagination

### ISSUE THREAD

**Issue by lednhatkhanh** [zeit/swr#17]
Wondering how I can apply pagination for my app using swr, I'm trying to use `swr` to implement infinite scroll for my web app and here are some questions:

- The query parameters will change: page = 1 then page = 2, how can I update the cache accordingly

Thank you.

**Comment by quietshu** [comment]
Hi @lednhatkhanh !

It is `useSWRPages`, wasn't included in version 0.0.2 and there's no docs about it yet. We just published it with 0.0.3. Also an example was added in https://github.com/zeit/swr/tree/master/examples/pagination.

If you need detailed docs, there're some comments and explanations on https://github.com/zeit/swr/blob/master/src/use-swr-pages.tsx and the example project.

**Comment by hackerabe** [comment]
Hi @quietshu wondering how [the example](https://github.com/zeit/swr/blob/master/src/use-swr-pages.tsx) would look if the limit changed, like in a button click.

**Comment by myspace24** [comment]
How to apply query params in useSWRPages?

**Comment by myspace24** [comment]
Hi, my pagination will apply filter function as well, I am facing the issue is when the search result is empty, even I change my search query, the SWR will not fetching the data again.

    const { pages,
        isEmpty,
        isLoadingMore,
        isReachingEnd,
        loadMore } = useSWRPages(
        'tenant-list',
        ({ offset, withSWR }) => {
            console.log(isActive, search);
            const { data } = withSWR(useSWR(['api/tenant', isActive, search, offset], fetcher));
            if (!data) {
                return _.times(2, (index) => {
                    return <Col key={index} span={24} className={'tenantCard'}>
                        <TenantSkeleton />
                    </Col>
                });
            }

            const { data: tenants } = data;

            return tenants.map((tenant, index) => (
                <Col key={index} xs={24} md={8} lg={6} className={'tenantCard'}>
                    <TenantDefaultCard tenant={tenant}/>
                </Col>
            ));
        },
        // one page's SWR => offset of next page
        ({ data: { pagination } }) => {
            if (!pagination) {
                return null;
            }
            if (pagination.current_page === pagination.last_page) {
                return null;
            }

            return pagination.current_page + 1;
        },
        [isActive, search]
    );
