### ISSUE TITLE
Is the advantage of SWR only in the first fetch?

### ISSUE THREAD

**Issue by jinxin0112** [zeit/swr#170]
If we get data through events, what's the advantage of swr

**Comment by quietshu** [comment]
I'm not sure what does "in the first fetch" mean, could you explain?

As for the second question, if you use event emitter to handle data fetching, you'll have to do more work to:
- subscribe event listeners for each component
- unsubscribe them when unmounting
- get the data on render
- deduplicate requests
- ...

For complex web apps, e.g.: say a page with 100 component instances, both of them require the data of some API, how can you make sure:
- they don't make duplicate requests
- their state are always consistent
- they will be re-rendered at the same time, ASAP, if the data changes
- they're still easy to maintain

If you try to simplify those processes with hooks, it will probably result in something similar to swr at the end.

Meanwhile, I'm working on a complex, real world SWR example too.

**Comment by quietshu** [comment]
Let me know if you have any further questions!
