### ISSUE TITLE
Using Classes with SWR vs Function - Example 

### ISSUE THREAD

**Issue by richardkeller411** [zeit/swr#175]
It looks like all of the examples are always functions so if refactoring pages to use swr with page classes do we need to convert to a function?  Having Classes helps

example:    class HomePage extends Page {}

**Comment by sergiodxa** [comment]
SWR is a hook, and hooks can't be used inside classes, maybe you could create a HOC or Render Prop wrapper of the hook and use it in your class-based component

**Comment by quietshu** [comment]
Hooks are only allowed in function components. You can also read this introduction of Hooks from the React team: https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy.
