### ISSUE TITLE
global-configuration problem

### ISSUE THREAD

**Issue by hitao123** [zeit/swr#179]
[global-configuration](https://github.com/zeit/swr#global-configuration)

i just config as the global-configuration, but the api still refresh per 3 seconds. 
you can fonund in repo [react-player-hooks](https://github.com/hitao123/react-player-hooks) when you visit http://localhost/blog/12, i do not want my api refresh

**Comment by quietshu** [comment]
Hi @hitao123, `refreshInterval` should be `0` by default. I think what you want might be `revalidateOnFocus: false`.

**Comment by hitao123** [comment]
@quietshu thanks , it can solve my problem
