### ISSUE TITLE
SWR requires a peer of react@16.11.0

### ISSUE THREAD

**Issue by Svish** [zeit/swr#180]
> swr@0.1.13 requires a peer of react@16.11.0 but none is installed.

Is it really necessary with such a specific peer dependency requirement as you have now?

```
  "peerDependencies": {
    "react": "16.11.0"
  }
```

The current React version is `16.12.0`, so on every `npm install` I now get warnings from `swr`. 😕

**Comment by wendellhu95** [comment]
```diff
- "react": "16.11.0"
+ "react": "^16.11.0"
```

**Comment by Svish** [comment]
@wendellhu95 That would be better, but still wouldn't accept `16.12.0`, would it?

Assuming react won't break anything until a new major version is released, and you do need at least version `16.11.0`, I guess it could be like this?

```
"react": ">= 16.11.0 < 17"
```

**Comment by wendellhu95** [comment]
`^` can cover any upcoming minor versions. It's equivalent to `>= 16.11.0 < 17`.

Messed it up with `~`?

**Comment by Svish** [comment]
@wendellhu95 Ah, then definitely `^` 👍

Just a newb who thought `^` was for the patch version and didn't even know `~` was a thing 😜
