### ISSUE TITLE
0.1.13 broke suspense (but the use case could be non standard)

### ISSUE THREAD

**Issue by Ankcorn** [zeit/swr#183]
After upgrading to 0.1.13 my dashboard had an error when loading saying "cannot get property Events of undefined"

Downgrading to 0.1.12 fixed the error. The getLotsOfThings function fetches a bunch of things so this might not be what useSWR is intended for. (but does make very easy 🎉 )

here is a code snippet to give some context
```

async function getLotsOfThings() {...}

const Dashboard = () => {
	const {data: { Events, Data },error} = useSWR([], getLotsOfThings, { suspense: true });
	

	return (
            ... lots of jsx and stuff
	);
};

export default function(props) {
	return (
		<Suspense
			fallback={
				<div className='center-child'>
					<Loader />
				</div>
			}>
			<Dashboard {...props} />
		</Suspense>
	);
}
```

**Comment by quietshu** [comment]
Yeah we fixed a bug and now using an empty array as the key will pause the fetching and return empty data (even in Suspense). So you can just use a string as the key:

```diff
-  useSWR([], getLotsOfThings, { suspense: true });
+  useSWR('get-things', getLotsOfThings, { suspense: true });
```

**Comment by Ankcorn** [comment]
thanks 😄
