### ISSUE TITLE
Performance: Component Re-rendered because of hook changes.

### ISSUE THREAD

**Issue by AnasBoulmane** [zeit/swr#184]
Make sure the state returned from the reducer is not a different object that equals by value but different by reference from the previous state:

![image](https://user-images.githubusercontent.com/17661697/70374958-27b02500-18f9-11ea-9097-52affdcc3d39.png)

**Comment by quietshu** [comment]
I think it’s because of the change of `isValidating` (the loading state), which is also returned by the hook.

**Comment by quietshu** [comment]
Will work on an improvement soon.
