### ISSUE TITLE
How to revalidate in paginate?

### ISSUE THREAD

**Issue by nghiepit** [zeit/swr#188]
Hi all,

I have a problem in pagination, I want to update each item in the page.

**For example**: I have a list notifications and button `Mark as read` in per notification.
After I successfully called APIs update for notification item, How to update this notification into list notifications in pagination current? Suppose, the current page is 2.

Thanks in advance.

**Comment by Ankcorn** [comment]
Could be an unhelpful work around but you could create a custom function to fetch a page of data and then make the cache key contain the page of data it is fetching. 

I.E.

```
async getPageOfData(page) {
  ...
}

function Notifications() {
  const { data, error, loading } = useSWR('page-2', getPageOfData)
  const markRead = async (notificationID) => {
    ...
    mutate('page-2', new data)
  }

  render (...)
}
```

**Comment by nghiepit** [comment]
I saw this example but did not find a solution.
Can you explain?

**Comment by quietshu** [comment]
If you are using `useSWRPages`, it returns a `pageSWRs` value which contains the SWR data of all pages. So you can do something like this:

```js
const { pageSWRs } = useSWRPages(...)

pageSWRs[1].revalidate()
``` 

Or, you can use the global `trigger` method to revalidate a specific key too.
