### ISSUE TITLE
Support render as you fetch exposing CONCURRENT_PROMISES

### ISSUE THREAD

**Issue by sergiodxa** [zeit/swr#190]
I'm working on an internal lib for my project where I'm using SWR to handle reading data and my lib to create, update and delete. In way to do prefetching simple I created functions to read data and use `mutate` to fill the cache. But my code ends up as:

```js
await api.users.findAll()
setShowUsers(true);
```

So I'm waiting for my first request to finish, fill the SWR cache, and then render. This it's not so different than just rendering and let SWR fetch it.

I was thinking with access to `CONCURRENT_PROMISES` I could make `findAll` save the promise of the fetch in that object and render my component using SWR immediately, doing something more similar to the render as you fetch pattern described in the React documentation.

With that my example would pass to be:

```js
api.users.findAll(); // start the request and save the promise in `CONCURRENT_PROMISES`
setShowUsers(true);
```

Eventually, with Concurrent Mode being stable, I could wrap that in a `startTransition`.

```js
startTransition(() => {
  api.users.findAll(); // start the request and save the promise in `CONCURRENT_PROMISES`
  setShowUsers(true);
});
```

**Comment by quietshu** [comment]
This is a good use case. But I think we can just reuse the `mutate(key, request)` function to do that right?

```js
mutate(key, asyncRequest)
// or
mutate(key, promise)
```

In these 2 cases we can just keep the promise in `CONCURRENT_PROMISES[key]` and everything else will stay the same. And I think it does what you need too.

**Comment by sergiodxa** [comment]
😮 I will try it and let you know if it works to close the issue.

**Comment by sergiodxa** [comment]
It works! 🎉
I will create an example 🔜
