### ISSUE TITLE
Upgrading from 0.1.12 to 0.1.13 broke the data-fetch

### ISSUE THREAD

**Issue by samsisle** [zeit/swr#191]
```JavaScript
...
  const {
    data
  } = useSwr(
    'https://api.themoviedb.org/3/movie/now_playing?page=1&language=en-US',
    { suspense: true }
  );

  console.log('data =', data);
...
```

This code will show data with `0.1.12`, but with `0.1.13` the data is coming back as undefined. The suspense boundaries are in the App component. I am using an experimental version of React (Concurrent-Mode) to enable data-fetching with Suspense.

## Dependencies
- [@reach/router](https://github.com/reach/router): `1.2.1`
- [react](https://github.com/facebook/react): `0.0.0-experimental-b53ea6ca0`
- [react-dom](https://github.com/facebook/react/tree/master/packages/react-dom): `0.0.0-experimental-b53ea6ca0`
- [react-scripts](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts) : `3.3.0`
- [swr](https://github.com/zeit/swr): `0.1.13`
- [unfetch](https://github.com/developit/unfetch): `4.1.0`

## Links

https://github.com/samsisle/react-experimental/blob/master/experiments/tmdb/src/index.js
https://github.com/samsisle/react-experimental/blob/master/experiments/tmdb/src/App.js
https://github.com/samsisle/react-experimental/blob/master/experiments/tmdb/src/components/movies/NowPlaying.js
https://github.com/samsisle/react-experimental/blob/master/experiments/tmdb/src/lib/fetch.js

**Comment by sergiodxa** [comment]
Not sure if it’s the reason but you don’t need concurrent mode to use suspense for data, I’m using it in production without concurrent mode

**Comment by samsisle** [comment]
Version `0.1.13` still doesn't work with or without concurrent mode. Another curious thing, without concurrent mode this console log (`console.log('data =', data);`) logs 8 times instead of 4 times with concurrent mode.

**Comment by samsisle** [comment]
Not sure what changes were made, but concurrent mode is working again with version `0.1.14` and `0.1.15`.

Thanks for the amazing work as always!

**Comment by quietshu** [comment]
Thanks for letting us know @samsisle 🙏 I'll create another issue to track it and add tests to make sure it doesn't break concurrent mode in the future.
