### ISSUE TITLE
When using SSR and initialData, is it possible to prevent first validation after render?

### ISSUE THREAD

**Issue by fi5u** [zeit/swr#194]
In `getInitialProps()` I call my fetcher function which queries the db for data. I pass that initial data to `useSWR` as `initialData` option. However, as soon as it renders, it queries the server again with the same end point (returning the same data set). I would expect that it would not query on render if `initialData` is passed, or there would be an option to prevent this.

I would like to prevent the server getting hit twice in a short timeframe with the same endpoint.

**Comment by quietshu** [comment]
Thanks for the great feedback!
