### ISSUE TITLE
Global fetcher undefined

### ISSUE THREAD

**Issue by rumpl** [zeit/swr#206]
Hi,

Thanks for the great lib. I think I found a bug or I'm not using it right, I took the global configuration from the examples but when ran I get an error (fn is not defined), you can see it [on this code sandbox](https://codesandbox.io/s/agitated-swartz-ygsfk)

**Comment by quietshu** [comment]
Hi @rumpl! Thanks for pointing out. This issue has been fixed in #196, I'll publish a new version of SWR soon so the fix will be included!

**Comment by rumpl** [comment]
Thanks!

**Comment by quietshu** [comment]
Published as `swr@0.1.14` :tada:

**Comment by rumpl** [comment]
💥 that was fast 🚀 

Thanks!
