### ISSUE TITLE
error type in TypeScript

### ISSUE THREAD

**Issue by dandrei** [zeit/swr#209]
Let's say I do this:

    const {data, error, isValidating, revalidate} = useSWR<DataType>("/url", myFetcher);

TypeScript tells me that `error` is typed to be `string`, but if inside `myFetcher` I run `throw Error("error message")`, then the type for `error` at runtime will not be `string`, but `Error`, causing a rendering crash if I try to treat it as text and include it in JSX.

What's going on here? Am I doing something wrong?

**Comment by aequasi** [comment]
The second generic property in `useSWR` is to specify the error type:

```typescript jsx
const {data, error, isValidating, revalidate} = useSWR<DataType, Error>("/url", myFetcher);
```

**Comment by dandrei** [comment]
Thanks, I hadn't realized that. That helps. Extra question: what would I need to throw to get a string? Tried `throw "message"` and that didn't work.

**Comment by aequasi** [comment]
use a promise with reject:

```typescript jsx
const myFetcher = (url) => {
	return new Promise((resolve, reject) => fetch(url).then((x) => x.json()).then(resolve, reject));
};
```
