### ISSUE TITLE
GraphQL documentation unclear

### ISSUE THREAD

**Issue by heymartinadams** [zeit/swr#222]
Apologies, to me your [GraphQL documentation](https://github.com/zeit/swr/blob/0cc1a56664ea85c4712fa7275ddf5c2102113669/README.md#data-fetching) on using custom variables for GraphQL doesn’t seem clear.  The [Multiple Arguments](https://github.com/zeit/swr#multiple-arguments) link you point to doesn’t list a single GraphQL example, only REST.

Would it be possible to be a bit more specific as to how you can pass a custom variable into the `swr` function?

**Comment by heymartinadams** [comment]
Looked up the `graphql-request` documentation, and attempted it this way, but still no go.
```js
const { data, error } = useSWR(apiAuthCodeGenerate, mutation =>
    request(API, mutation, { mobile })
  )
  console.log({ data, error })
```

**Comment by quietshu** [comment]
Thanks for letting me know @heymartinadams. We'll improve the documentation of GraphQL with variables!
