### ISSUE TITLE
How do you recommend mutating data that is returned by multiple endpoints?

### ISSUE THREAD

**Issue by derindutz** [zeit/swr#226]
For example, say I have two components, A and B. A uses `/messages?before=2020-01-12&after=2020-01-10`. B uses `/messages?starred=true`. Let's say the user stars a message with id `message-8` from 2020-01-11 in component B and we issue a POST to star the message. If we just called `mutate('/messages?starred=true', [...otherMessages, {...message, is_starred: true}])`, B would be up-to-date and show the starred message, but A wouldn't. 

Would you recommend keeping a mapping from object id to URLs that we could use to call mutate with all the URLs? In the example above, the map would be `{'message-8': ["/messages?before=2020-01-12&after=2020-01-10", "/messages?starred=true"]}`. Or is there something else that would be better?

And a big thank you for all your work on this awesome project!!!

**Comment by rmacy** [comment]
I think one very easy, maybe naive, way to handle this is to move your filtering onto the client, and use the same key `/messages` for all of your requests.

Another approach could be to pass your query params into your fetcher function to keep the filtering server-side, but force a common key (again `/messages`) client-side. E.g.

```js
  const { data } = useSWR(`/messages`, fetcher: url => fetch(`${url}?${params}`))
```
