### ISSUE TITLE
How can I update a state used on an Input field

### ISSUE THREAD

**Issue by ivanhueso** [zeit/swr#232]
How can I update setName from the data coming from useSWR hook? Where name should be populated with data.name

```
const [name, setName] = useState()
const { data } = useSWR("/api/me", fetcher)
 
<input value={name} onChange={e => setName(e.target.value)} />

```

**Comment by sergiodxa** [comment]
You could run an effect.
```js
useEffect(() => {
  setName(data.name)
}, [data.name])
```
Now every time `data.name` change it will update the `name` state, note this will overwrite any change the user has made and was not saved.

**Comment by pacocoursey** [comment]
Closing as this has been answered and is more of a question about React in general :)
