### ISSUE TITLE
How can I cancel Interval polling?

### ISSUE THREAD

**Issue by zhangking** [zeit/swr#236]
I use refreshInterval to implement the Interval polling. But I'd know how to cancel it when it's running

**Comment by quietshu** [comment]
You can use a state for the interval, and set it to 0 when you want to cancel:

```js
const [int, setInt] = useState(3000)
const { data } = useSWR('/api', fetcher, { refreshInterval: int })

return <button onClick={() => setInt(0)}>cancel</button>
```

**Comment by zhangking** [comment]
thks

**Comment by Gavinchen92** [comment]
> You can use a state for the interval, and set it to 0 when you want to cancel:
> 
> ```js
> const [int, setInt] = useState(3000)
> const { data } = useSWR('/api', fetcher, { refreshInterval: int })
> 
> return <button onClick={() => setInt(0)}>cancel</button>
> ```

dont work

**Comment by quietshu** [comment]
@Gavinchen92 Can you give me more details? Here's a working example: https://codesandbox.io/s/exciting-zhukovsky-jxm18

**Comment by SevenOutman** [comment]
Same problem here. In React devtools you see `refreshInterval: 0` in useSWR hook, but the polling doesn't stop.
