### ISSUE TITLE
Revalidation even if data is already cached & revalidateOnFocus is false.

### ISSUE THREAD

**Issue by omerman** [zeit/swr#257]
Hi, First of all thanks for this rocking lib. Im exploring it these days, its awesome.

Now to my issue,
I'm rendering a component that uses useSWR like such -> useSWR('key', fetcher).
After the component unmounts, and re-mounts again, Im noticing that the useSWR does infact bring back the cached results, but it also triggers a revalidation.

1. Is this the expected behavior?
2. If so, can you please supply a flag indication to cancel it? locally & globally

Thanks, Looking forward for your response

**Comment by sergiodxa** [comment]
That is an intended behavior, the name of the library comes from the idea to first show stale data then revalidate it against the API and update it to show the correct data (stale-while-revalidate aka SWR).

There is a PR https://github.com/zeit/swr/pull/225 intended to add a flag to set SWR to don't revalidate the cache on mount and let you manually do it if you want (it will still fetch it if it wasn't already provided with the `initialData` option).

**Comment by omerman** [comment]
Thank you, It took me a while to grasp the concept :) Thanks again for your quick response.
