### ISSUE TITLE
useSWR with suspense triggers infinite rendering loop

### ISSUE THREAD

**Issue by jannisg** [zeit/swr#260]
Seems to be similar to/a regression of #46.

With `{ suspense: true }` for `useSWR` the `fetcher` function is triggered but the promise is not awaited and an infinite loop occurs.

A reproduction is available at: https://codesandbox.io/s/reactsuspense-useswr-b1jin

The versions (as per the codesandbox) are:
- `react@16.12.0`
- `react-dom@16.12.0`
- `use-swr@1.0.3`

Apologies if this is user error but I can't seem to figure this one out.

**Comment by quietshu** [comment]
The package name should be `swr`, not `use-swr` (which was deprecated already) :)

**Comment by jannisg** [comment]
Oops, well that is embarrassing :|
Thanks for pointing this out though :)
