### ISSUE TITLE
Dedupe after mutation. 

### ISSUE THREAD

**Issue by omerman** [zeit/swr#267]
My use case -

User clicks a button, I then want to prefetch the data, and store the data using the mutation api.
once i finished storing the data i trigger a state change that renders a component
That uses the results I just prefetched, using the useSWR hook.

The problem is that the useSWR triggers the request again(revalidates) ..
I think that the dedupe behavior should also take into account the mutations, and not only the hook calls. Meaning if i mutated a key in less than the time specified in the dedupe interval, a revalidation should be skipped.

What do you think? 

Thanks in advance, loving the library :)

**Comment by quietshu** [comment]
Hi @omerman, the `mutate` function has a third parameter `shouldRevalidate`. So you can pass `false` to turn off revalidation after mutating data:

```js
mutate('key', newData, false)
```

**Comment by omerman** [comment]
@quietshu I'm familiar with the `shouldRevalidate` , I'll try to show a better example:


```

// Keep in mind this component will be rendered only after the search button is clicked.
// so it will trigger a revalidation.. but it is displayed right after I mutate the same key.. So I expected a dedupe to kick in..(a dedupe that will be set by the mutation side)
const SearchResults = () => {
  const results = useSWR('search-results', fetcher);

  return <div>{JSON.stringify(results)}</div>;
}

const Search = () => {
  const [loadingResults, setLoadingResults] = useState(false);
  const [displayResults, setDisplayResults] = useState(false);
 
  const search = useCallback(async () => { 
         setLoadingResults(true); 
         const searchResults = await getResults();
        mutate('search-results', searchResults, false); // hoping for this to add dedupe in case of someone using useSWR right after the mutate was finished.
       setDisplayResults(true); // SearchResults will be rendered now.
    }, []);

  return (
    <div>
      {loadingResults ? 'Loading' : null}
      <button onClick={ () => mutate('search-results', nextData, false) }>Hi</button>
      <button onClick={ () => setDisplayResults(false) }>Clear</button>
      { displayResults && <SearchResults /> }
    </div>
  )
}
```
