### ISSUE TITLE
Allow mocking and typing

### ISSUE THREAD

**Issue by jantimon** [zeit/swr#27]
swr looks really cool 👍

I played around with something similar for request-registry recently.

What I miss in `swr` over request-registry is the ability to define typings, dependencies and to mock  
I would love to know what you think about those features.

### Define typings once per endpoint

In request registry you define endpoints e.g.:

```ts
import { createGetEndpoint } from "request-registry";
 
// Define a service endpoint to load user information
const userEndpoint = createGetEndpoint<{id: string}, {name: string, age: number}>({
    url: keys => `http://example.com/user/${keys.id}`
});
```

Then you can use them from a hook e.g.

```ts

import {useGetEndPointSuspendable} from 'request-registry-react';

const UserDetails = props => {
    const { name } = useGetEndPointSuspendable(userEndpoint, { id: props.id });
    return <div>{name}</div>;
};
```

It also works without suspense similar to the swr api:

```ts
const UserDetails = props => {
    const endpointState = useGetEndPoint(userEndpoint, { id: props.id });
    if (!endpointState.hasData) {
        return <div>Loading...</div>;
    }
    const { name } = endpointState.value;
    return <div>{name}</div>;
};
```

This allows autocomplete and type checking for `endpointState.value` without writing additional endpoint specific types inside the UserDetails component.

### Dependencies

Endpoints can also cause mutations e.g.:

```ts
import { createPostEndpoint } from "request-registry";
 
// Define a mutation endpoint
const mutateUser = createPostEndpoint<{id: string}, {name: string}, {}>({
    url: keys => `http://example.com/user/${keys.id}`
    // Invalidate all userEndpoint endpoints (similar to your trigger broadcast)
    afterSuccess: () => userEndpoint.refresh()
});

// now for example inside an eventHandler 
  <button onClick={async () => {
      const newName = data.name.toUpperCase()
      // update user 4 and rerender all components which rely on user 4 data:
      await mutateUser(newName)
    }}>
```

### Mocking

For unit tests and storybook we sometimes want to tryout specific scenarios and want to mock backend responses.

```ts
// Define your mock data for getUserName
// Typescript will tell you if the mock data doesn't match the types for
// getUserName
const userJoeMock = createMockEndpoint(getUserName, async () => ({
    name: 'Joe',
}));
```

Now in any unit test or story you can activate the mock:

```ts
// Activate mock:
userJoeMock.activate();
// Deactivate mock:
userJoeMock.clear();
```

There are more utils around this but maybe this is enough to get the basic idea.

I would love to know what you think about those features. :)

**Comment by sergiodxa** [comment]
I think you could create a custom hook using SWR internally and define the types there.

```ts
type User = {
  id: number,
  displayName: string
}

function useUser(id: number): { data: User } {
  return useSWR(`/api/users/${id}`, fetch);
}

function UserProfile({ id }: { id: number }) {
  const { data } = useUser(id);
  return <p>{data.displayName}</p>
}
```

Something like this, and if you move this custom hook to another file you could mock it in your tests.

**Comment by sergiodxa** [comment]
Maybe those custom hooks could even be automatically created along it's types with a script reading the type definitions of the API endpoints and the list of endpoints

**Comment by quietshu** [comment]
Thanks @sergiodxa ! 👍 Yeah that's what we're currently doing on zeit.co. We created different SWR based hooks for different resources, so it won't be that difficult to switch / mock.

**Comment by jantimon** [comment]
@quietshu @sergiodxa using a wrapping hook is a great idea 👍

Can you show me an example how such mocking could look like?

**Comment by sergiodxa** [comment]
In just you could do:

```js
import useUser from "path/to/hooks/api/use-user";

jest.mock("path/to/hooks/api/use-user");

useUser.mockImplementation(() => ({
  data: {
    displayName: "sergio", id: 1
  }
}));
```

Something like that will mock useUser module and let you mock the implementation to return fake data immediately, you could also run `mockImplementation` multiple times to change what it will return.

**Comment by jantimon** [comment]
Would that also work for storybook (or similar tools) or only for jest?

**Comment by sergiodxa** [comment]
I have never mocked anything in storybook, for other testing frameworks like Jest I suppose they have their own implementations of the same

**Comment by aequasi** [comment]
Note that return/error types are introduced by my last PR, and i think were just released

**Comment by ryanlanciaux** [comment]
@jantimon I know it's only a year after you asked this BUT I use MirageJS when I need to mock something in Storybook. 

Thread on how to achieve this here: https://twitter.com/ryanlanciaux/status/1288897760473882625

**Comment by sandinmyjoints** [comment]
@jantimon For storybook, we've updated our fetcher implementation to know when it's running in the context of storybook (there a variety of ways you could do this, one is to set an env var when starting storybook then look for it on `process.env`), and when that's the case, rather than run a real fetch, it returns whatever is in `global.storybookData[key]`. Then in our stories for components that use swr hooks, we set `global.storybookData` as appropriate for that story. We also implemented a hook that whenever the story being rendered switches, we call `cache.clear` to clear the swr cache so the new story doesn't return swr's cached data for the previous story.
