### ISSUE TITLE
[Question]: is it as designed that trigger and mutate will follow dedupingInterval

### ISSUE THREAD

**Issue by mxschmitt** [zeit/swr#271]
Hey,

small question: is it as designed, that a manual trigger will follow the `dedupingInterval` and don't invalidate the cached item if it was less than the `dedupingInterval`?

Example: https://codesandbox.io/s/quirky-albattani-ttfrw

Expected: On each button click the new time will be fetched

Actual: It only will be fetched if I click slower than 200ms (default `dedupingInterval`)

Version: 0.1.17

**Comment by rtxu** [comment]
I encountered the same situation.

Not only `trigger`, but also `mutate` will be omitted when it starts in less than `dedupingInterval` since the latest revalidate.

swr version：0.1.12
default `dedupingInterval`: 2000ms

**Comment by quietshu** [comment]
This could be a bug. By design `trigger` or `mutate` should never be deduped.
