### ISSUE TITLE
Setting max retryCount on error

### ISSUE THREAD

**Issue by dominictwlee** [zeit/swr#276]
Is there a way to add a max retryCount on error without overriding the entire onErrorRetry? I think it'd be nice to be able to keep the very reasonable default behaviour of exponential backoff and stopping on ```!isDocumentVisible()```, but be able to tweak and limit max tries via config.

What do you think?

**Comment by sergiodxa** [comment]
This would be really nice, if you have an API always throwing it will continue requesting forever.
