### ISSUE TITLE
mutate and revalidating 

### ISSUE THREAD

**Issue by dastrong** [zeit/swr#299]
`mutate('/api/user', newUser, false)      // use `false` to mutate without revalidation`

It's not possible now, but it would be nice, if I could set the `revalidating` boolean depending on the outcome of that newUser promise.

**If it's successful:**
- I can mutate it myself and don't need to revalidate

**If it's unsuccessful:**
- I could return my original values, but I'd like to revalidate

**Comment by aequasi** [comment]
You can do this with just js:

```js
newUser
    .then((user) => mutate('/api/user', user, false))
    .catch(() => revalidate('/api/user'));
```

**Comment by dastrong** [comment]
That could work, but I'm using variables from the cache to make an API call.

[I also found these examples using the `mutate` function passed from yout `useSWR`](https://github.com/zeit/swr/issues/155#issuecomment-559190110)

Btw, I saw that they were depreciating `revalidate` in the future from the previous issue (#298)

I'll close since there are other ways to accomplish what I was looking for.
