### ISSUE TITLE
Fetch only on first change and then don't

### ISSUE THREAD

**Issue by jansedlon** [zeit/swr#314]
Hello, imagine that you have a button that shows and hides a hidden content. When the hidden content shows, I want to use SWR to make a request and cache it. However it should not do it when I close it and open it again.

When I use it like this, it process the request again and again. Is there a way to disable it by default and then call some function to trigger it?

My problem is that I have a Filters component which contains a lot of components like this and I don't want all of them to fetch some data at once.

```typescript
const SportFilter: React.FC = () => {
  const [searchedSport, setSearchedSport] = useState<string>('');
  const [selectedSports, setSelectedSports] = useState();
  const [showFilterContent, setShowFilterContent] = useState<boolean>(false);
  const { data: sports } = useSWR('sport-categories', apiClient);

  const toggleFilterContent = (e: React.MouseEvent): void => {
    setShowFilterContent((prev) => !prev);
  };
  return (
    <StyledSportFilterContainer>
      <Button onClick={toggleFilterContent}>Sport</Button>
      <StyledSportFilterContent show={showFilterContent}>
        <Input placeholder="Zadejte sport" value={searchedSport} onChange={(e) => setSearchedSport(e.target.value)} />
        <Separator />
        <StyledSportList></StyledSportList>
      </StyledSportFilterContent>
    </StyledSportFilterContainer>
  );
};
```

**Comment by sergiodxa** [comment]
You can disable all revalidations using:

```js
useSWR(key, fetcher, {
  revalidateOnFocus: false,
  revalidateOnReconnect: false,
});
```

That will disable default revalidation, the only way now to revalidate will be to render a component using the same key or calling `mutate(key)` to trigger it manually.
