### ISSUE TITLE
Does ZEIT use Redux?

### ISSUE THREAD

**Issue by timurmaio** [zeit/swr#315]
Hello! Our team is in the early stage of the web app development and we adopted react/redux. We tried SWR on one page and it works great, much simpler that redux for API calls. Can you please share the experience, does ZEIT use Redux, or useSWR covers all cases?

**Comment by neolefty** [comment]
@timurmaio Have you considered `useReducer()` as a simpler substitute for Redux? Commentary here: https://www.robinwieruch.de/redux-vs-usereducer

We're using it and finding it to have less boilerplate than "old" Redux (pre-hooks), but I haven't compared it to "new" Redux using all of its new hooks.

**Comment by sergiodxa** [comment]
Mentioning @rauchg @pacocoursey @quietshu who could answer this better (btw would be great to have discussions enabled in this repo too 😉😉).

**Comment by pacocoursey** [comment]
No, we don't use redux or any state management libraries like redux at ZEIT. So far we've found SWR to be a reliable and much simpler alternative to remote data management across our dashboard.

We do use `useReducer` to minimize re-renders and manage complex state, though!
