### ISSUE TITLE
How to signal errors on custom fetcher

### ISSUE THREAD

**Issue by ranisalt** [zeit/swr#329]
Documentation usually assumes the fetcher will never fail, but sometimes it may and it is unclear how to handle this.

My fetcher is:
```ts
const ajax = async <Res, Req>(url: string): Promise<Res> => {
	const resource = new URL(url, config.api_url);
	const init: RequestInit = { credentials: 'include', mode: 'cors' };

	const response = await fetch(resource.href, init);
	const body = await response.text();
	if (!response.ok) {
		throw new Error(body && body.length > 0 ? JSON.parse(body) : response.statusText);
	}
	return body && body.length > 0 ? JSON.parse(body) : null;
}

export const useAuth = () =>
	useSWR<User>('/auth', ajax, {
		revalidateOnFocus: false,
		shouldRetryOnError: false,
		suspense: true,
	});
```

However my API returns status 401 Unauthorized when the user must be logged in to view the resource, but the code above crashes instantly with the error:
```
utils.ts:41 Uncaught Error: 401
    at ajax (utils.ts:41)
```

So it seems the returning promise is not checked for rejection. How can I tell that the request has failed when using this fetcher?

**Comment by shuding** [comment]
Since you are using React Suspense, SWR will not catch the errors thrown inside the fetcher. You will need to use Error Boundary to handle it yourself. React docs: https://reactjs.org/docs/concurrent-mode-suspense.html#handling-errors

```js
      <ErrorBoundary fallback={<h2>Could not fetch posts.</h2>}>
        <Suspense fallback={<h1>Loading posts...</h1>}>
          <ProfileTimeline />
        </Suspense>
      </ErrorBoundary>
```

**Comment by ranisalt** [comment]
Ah, that makes sense. I tried to find it in the website, sorry for that.
