### ISSUE TITLE
How to support page jumping when using `useSWRPages`?

### ISSUE THREAD

**Issue by Evian-Zhang** [zeit/swr#354]
I use pageIndex as offset to paginate in backend. So I want users at page 1 to be able to click page 3 and then get the data of page 3.

It seems that `useSWRPages` only support jump to next one page (by `loadMore`) and previously loaded pages. How can I get arbitrarily page jumping?

**Comment by sergiodxa** [comment]
The useSWRPages hook is intended for infinite scrolling, in your case it’s easier to keep the page number in a state and update the useSWR key to trigger a new fetch.
