### ISSUE TITLE
What's the pattern to only read key data without fetching?

### ISSUE THREAD

**Issue by bausk** [zeit/swr#360]
Suppose I have two pages for listing some REST objects and for showing details for those objects, explore/index.js and explore/[id].js. They fetch a list of objects and details, using respectively `useSWR('/api/objects', fetcher)` and ```useSWR(`/api/objects/${router.query.id}`, fetcher)```.

How do I use the `/api/objects` state as initialData on the details page? When `[id].js` renders (normally soon after visiting `index.js`), I don't care how stale the list is, I only want to use it to pre-populate my state while the second endpoint is being fetched so I don't want to make an additional API request to /api/objects.

An IMO good use case is when fetching the list is cheap (ids/names of objects) but fetching the details is expensive (e.g. it returns DB statistics or logs).

So far I've considered providing a no-op fetcher, which feels really dirty:

```
// in [id].js
useSWR('/api/objects', async () => {
        throw new Error();
    }, {
        revalidateOnFocus: false,
        revalidateOnReconnect: false,
    });
```

Or, since we cannot pass props from page to page in Next.js, use duplicate state source like context or MobX store which feels equally dirty.

What's the best way to solve this, or am I completely astray in approaching this problem?

Thanks for your time!

**Comment by sergiodxa** [comment]
If you don’t care about data being stale you can read from cache directly using cache.get(key), you could even subscribe to cache updates with cache.subscribe(fn) and update a state with the cache data but never trigger a request. But if you will subscribe I recommend you to use useSWR directly.

**Comment by karlguillotte** [comment]
I have the same use case. 

Where can I get documentation about that `cache`? 

Thanks!

**Comment by sergiodxa** [comment]
The best place right now is the code itself https://github.com/zeit/swr/blob/master/src/cache.ts

**Comment by karlguillotte** [comment]
Great thanks @sergiodxa ! 

That is what I did. I wanted to ask, because it was not documented and I want to make sure to use API that is stable.

**Comment by bausk** [comment]
Thanks for your reply @sergiodxa!

Here's the custom hook I came up with that implements the following use case pattern:
- do not invoke any automatic validation -- that is, on render, focus, or reconnect;
- until prompted by user event to validate manually, use cached value from cacheKey;
- user code can invoke onFetch to validate fetchKey and use its result from now on.

I'd be happy to discuss any problems with this approach. It's a bit verbose and it would be good to know if similar behaviour can be implemented in a better way.

Obviously, passing stuff like `error` etc. should also be added to get true composability, this is a minimal variant.

```
import React, { useState } from 'react';
import useSWR, { cache } from 'swr';

const useManualSWR = (cacheKey, fetchKey, fetcher) => {
    const [ startFetch, setFetch ] = useState(null);
    const cachedData = cache.get(cacheKey);
    const { data: frechData, mutate, isValidating } = useSWR(
        () => startFetch ? fetchKey : null,
        fetcher,
        {
            revalidateOnFocus: false,
            revalidateOnReconnect: false,
        }
    );
    const onFetch = () => {
        if (startFetch) {
            mutate();
        }
        setFetch(true);
    };
    const data = frechData || cachedData;
    return { onFetch, data, isValidating };
}

export default useManualSWR;
```

**Comment by sergiodxa** [comment]
I think `cacheKey` and `fetchKey` should be the same, if the idea to have different ones is to support arrays in `fetchKey` then it's not needed, `cache.key` supports arrays too, so you can pass the same key to both keys, it even supports functions.

Also this `() => startFetch ? fetchKey : null` doesn't need to function, with only the condition is enough to avoid the fetch until `startFetch` is true 👍 

```js
import React, { useState } from 'react';
import useSWR, { cache } from 'swr';

const useManualSWR = (key, fetcher, options) => {
    const [ startFetch, setFetch ] = useState(null);
    const cachedData = cache.get(key);
    const { data: fetchData, mutate, isValidating } = useSWR(
        startFetch ? key : null,
        fetcher,
        {
            ...options, // options is before the other keys so you can't overwrite them
            revalidateOnFocus: false,
            revalidateOnReconnect: false,
        }
    );
    const onFetch = () => {
        if (startFetch) {
            mutate();
        }
        setFetch(true);
    };
    const data = fetchData || cachedData;
    return { onFetch, data, isValidating };
}

export default useManualSWR;
```

Something like that ☝️

**Comment by bausk** [comment]
Thanks a lot! cacheKey and fetchKey might be different not because of arrays but because I might want to get cache from a different API call; I'm not convinced that's useful though.

My previous version didn't fulfil the "no auto fetching" requirement when I introduced variable keys -- my use case is a data chart that shows data that can be fetched (via an expensive call to BigQuery) within different intervals so start and end must go into the key to become available to the fetched function, and startFetch flag remains true after key change, prompting fetch on rerender. After some errors I added the following useEffect, which seems to be the only way to reliably prevent autofetch:

import React, { useState, useCallback, useEffect } from 'react';
import useSWR, { cache } from 'swr';

```
const useManualSWR = (cacheKey, fetchKey, fetcher, options) => {
    const [ startFetch, setFetch ] = useState(false);
    const cachedData = cache.get(cacheKey);
    const { data: fetchData, mutate, isValidating } = useSWR(
        () => startFetch ? fetchKey : null,
        fetcher,
        {
            ...options,
            revalidateOnFocus: false,
            revalidateOnReconnect: false,
        }
    );
    useEffect(() => {
        if(!isValidating) {
            setFetch(false);
        }
    }, [isValidating]);
    const onFetch = useCallback(() => {
        if (startFetch) {
            mutate();
        }
        setFetch(true);
    }, [startFetch]);
    const data = fetchData || cachedData;
    return { onFetch, data, isValidating };
}

export default useManualSWR;
```

My takeaway from this is that SWR is more geared towards handling immediate UI changes rather than explicitly on-demand changes and there's some shoehorning going on with my approach. I'm still going to try using this because it's convenient to have the single library for all data calling stuff.

Thanks again!

**Comment by sergiodxa** [comment]
@bausk actually I think this https://github.com/zeit/swr/pull/225 will let you implement what you want, disabling `revalidateOnMount` would make SWR only read from cache until you manually trigger a revalidation with `mutate`.

**Comment by bausk** [comment]
@sergiodxa Seems to be exactly what I need, thanks!
