### ISSUE TITLE
`swr@0.2.0` introduced stale data issue not present in `swr@0.1.18`

### ISSUE THREAD

**Issue by NoahZinsmeister** [zeit/swr#361]
I'd like to report a bug which, as far as I can tell, was introduced in `swr@0.2.0`.

Reproduction: https://codesandbox.io/s/epic-goodall-8cpmn

As you can see in the reproduction above, while the UI always displays the correct data for the given inputs, the console reveals that there are render cycles for which the data returned from `useSWR` do _not_ match the inputs supplied by the user. If you switch the dependency from `swr@0.2.0` to `swr@0.1.18` and refresh the page you'll notice that the console indicates no errors.

**Comment by Svish** [comment]
Discovered same bug here, so we're unable to upgrade for now as well 😕
