### ISSUE TITLE
onSuccess callback on useSWR not receiving data

### ISSUE THREAD

**Issue by sfdcale** [zeit/swr#362]
I am trying to use `onSuccess` callback function on useSWR with no success, here is the simplified but reproducible code:

```
useSWR("/api/data", fetcher, { onSuccess: 
    (data, key, config) => {
      console.log('Entered onSuccess'); 
      console.log({data}); //This always prints undefined.
    }
  }
);
```

**/api/data.js:**
```
export default (req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json');
    res.send({ FirstName: "John", LastName: "Doe"});
}
```
**package.json**:
```
"next": "^9.0.6",
"swr": "^0.2.0"
```

Here is the codesandbox showing the problem : https://codesandbox.io/s/nervous-hill-mn0kz?file=/pages/index.js

**Comment by sfdcale** [comment]
Can someone help me with this?

**Comment by huozhi** [comment]
hi @sfdcale I checked the codesandbox link you post above. looks like you missed `return` for fetcher. it works after adding the `return` keyword

```diff
const fetcher = url =>
    fetch(url).then(r => {
-      r.json()
+      return r.json();
    });
```

**Comment by sfdcale** [comment]
@huozhi  Thanks so much for looking into it.
