### ISSUE TITLE
How to revalidate with multiple arguments?

### ISSUE THREAD

**Issue by iammarkps** [zeit/swr#363]
https://github.com/zeit/swr#multiple-arguments and mutate()

**Comment by sergiodxa** [comment]
You can pass multiple arguments to mutate, if you have
```js
useSWR(["/api/users", 1], fetcher);
```

You can do

```js
mutate(["/api/users", 1]);
```

**Comment by marsonmao** [comment]
Any possible reason that `mutate(["/api/users", 1]);` is not triggering `fetcher`?
I'm doing the same setup, but `fetcher` is not fired.

**Comment by yzi-yzi** [comment]
> Any possible reason that `mutate(["/api/users", 1]);` is not triggering `fetcher`? I'm doing the same setup, but `fetcher` is not fired.
> 
> I can only succesfully fire `fethcer` if my key stays with pure string like `useSWR("/api/users", fetcher);` + `mutate ("/api/users")`.

I got the same issue here, do you have any solution?
