### ISSUE TITLE
How to use with AsyncStorage in React Native

### ISSUE THREAD

**Issue by FrozenIce0617** [zeit/swr#368]
Now I'm working on React Native with `swr`.

We have to save the token to AsyncStorage in React Native.

```
import { AxiosRequestConfig } from 'axios';
import { getHeaders } from '../../util/apiUtil';

export const getCustomerInfo = async (): Promise<AxiosRequestConfig> => {
  const token = await getHeaders();
    
  return (
    method: 'GET',
    url: `https://xxxxxxx.com/xxx/xxx`,
    headers,
  );
}
```

In the User screen, we have to use SWR hook.

As you know, React Hooks must be called in the exact same order in every component render.

What should I do to resolve this issue?
Is it impossible to use SWR with AsyncStorage in React Native?

Any help would be appreciated.

**Comment by sergiodxa** [comment]
You can read from AsyncStorage in the fetcher, another option is to pass the token in the key (the key could be an array) so if the token changes the queries will run again

**Comment by FrozenIce0617** [comment]
Would you like to provide a sample code snippet that enables us to read the token from AsyncStorage in the fetcher?
