### ISSUE TITLE
What's the recommended way to use a dynamic number of SWRs?

### ISSUE THREAD

**Issue by derindutz** [zeit/swr#371]
Hi!

First, thank you for building and maintaining this amazing library!

Second, while using it, I often find myself needing a dynamic number of SWRs. Is there a best practice for doing this?

I've included how I currently do it below. I read through the use-swr-pages code and tried to do something similar. I'd really appreciate it if you could let me know if there's a better way!

This is how the API is used:
```
function ChannelUsers({ channel }) {
  const {
    fetcherComponents: channelUserFetcherComponents,
    swrs: channelUserSWRs,
  } = useSWRs(channel.userIds.map(userId => userURL(userId)));

  const users = channelUserSWRs.map(swr => swr.data);

  return <div>
    {channelUserFetcherComponents}
    { /* render data here */ }
  </div>;
}
```

And this is how it's implemented:
```
export function useSWRs(keys: (string | null)[] | null) {
  const [swrs, setSWRs] = useState([]);

  const keysRef = useRef(keys);
  const prevKeys = usePrevious(keys);
  if (!isEqual(keys, prevKeys)) {
    keysRef.current = keys;
  }

  const fetcherComponents = useMemo(() => {
    return !keys
      ? null
      : keys.map((key, index) => {
          const Page: FC = () => {
            const swr = useSWR(key);
            setSWRs((swrs) => {
              const _swrs = [...swrs];
              _swrs[index] = {
                data: swr.data,
                error: swr.error,
                revalidate: swr.revalidate,
                isValidating: swr.isValidating,
                mutate: swr.mutate,
              };
              return _swrs;
            });
            return null;
          };
          return <Page key={key ? key : undefined} />;
        });
  }, [keysRef.current]);

  return { fetcherComponents, swrs };
}
```

**Comment by sergiodxa** [comment]
Based on your example, I would have created a User component and a UserList, the UserList does the initial fetch to get the ids and render a list of User components that fetch each user data individually.

**Comment by derindutz** [comment]
Thank you for your feedback! What would you recommend if I want the UserList component to have the data of each user? It's not going to be displaying actual User components - rather, it's going to be doing some processing with the data (i.e. getting the average user age, initiating another fetch for more data based on the user objects,...) and displaying something based on that processed data. 

Would you still suggest doing something similar to what you suggested: Have each User component render null and pass a callback to each User component that sets some state in the UserList component?

**Comment by sergiodxa** [comment]
I would update the API to give me more than the ids

**Comment by derindutz** [comment]
Yep, that's a good option in this case. What I'm gathering is: it's not recommended to try using a dynamic number of SWRs as I did and I should try to avoid it if possible. In particular, rendering components that don't do anything except fetch data is something to avoid if possible. Assuming that's roughly correct, I'm going to close this for now. But please re-open it if there's something left to explore. Thank you for your help @sergiodxa!
