### ISSUE TITLE
How to use SWR if the query params tends to change??

### ISSUE THREAD

**Issue by sainhimanshu9** [zeit/swr#376]
Currently i'm reusing a component, when component mounts, i made an api call,
sourceProp is a prop(like its name suggests) i get from the parent component.

useEffect(() => {
    let mounted = true;
    const fetchData = async () => {
      try {
        setLoading(true);
        const res = await axios.get(url, {
          sourceParam: sourceProp,
          ...filters,
          offset: page * rowsPerPage,
          limit: rowsPerPage,
        });
if (mounted) {
          setData(res);
          setLoading(false);
        }
      } catch (error) {
        //errorhandled
        
        setLoading(false);
      }
    };
    fetchData();
    return () => {
      mounted = false;
    };
  }, [sourceProp, page, rowsPerPage, filters]);

As the source prop changes the new data will come...but every time user comes to a component, the loader runs which is why i want to use SWR, like this.

const fetcher = async (arg) => {
   const res = await axios.get(arg);
    return res;
  };

const { data, error } = useSWR(
    `${url}?source=${soureProp}`,
    fetcher,
    {
      dedupingInterval: 5000,
    }
  );

till here i'm getting it correct but how can i associate my other params(which are not stable) as using them as args in array either break the cache or unlimited rendering.

**Comment by sergiodxa** [comment]
You can use an array as key and pass more valued your fetcher will receive those values as normal arguments (not as an array)

**Comment by sainhimanshu9** [comment]
@sergiodxa 
i've done that but the params are not stable, so it breaks the cache... they are stored in key value pairs where values are state which keep on changing. i've read your comment where you have said that params should be passed individually but doing this `const { data, error } = useSWR(
    [url,sourceParam: sourceProp,
    ...filters,
    offset: page * rowsPerPage,
    limit: rowsPerPage], 
    fetcher,
    {
    dedupingInterval: 5000,
    }
    );` is a wrong syntax, so how should move ahead?

**Comment by sergiodxa** [comment]
Is there a reason to don’t use it to build the final URL before calling SWR? Ask you can pass a string

You could create a custom hook which receives an object with your parranda and format the URL and then call SWR

**Comment by sainhimanshu9** [comment]
@sergiodxa  Thanks it worked.

**Comment by thiagoconnectcom** [comment]
can you put here the way you used to solve?

**Comment by mazWaz** [comment]
> @sergiodxa
> i've done that but the params are not stable, so it breaks the cache... they are stored in key value pairs where values are state which keep on changing. i've read your comment where you have said that params should be passed individually but doing this `const { data, error } = useSWR( [url,sourceParam: sourceProp, ...filters, offset: page * rowsPerPage, limit: rowsPerPage], fetcher, { dedupingInterval: 5000, } );` is a wrong syntax, so how should move ahead?

i use like this but my tigger and mutate not response

**Comment by jeff-kilbride** [comment]
@thiagoconnectcom Something like this:
```javascript
import useSWR from 'swr';

/**
 * Re-usable SWR api implementation.
 *
 * @param {string} url
 * @param {object} params
 * @returns object
 */
function useApi(url, params) {
  const usp = new URLSearchParams(params);

  // Create a stable key for SWR
  usp.sort();
  const qs = usp.toString();

  const { data, error } = useSWR(`${url}?${qs}`);

  return {
    loading: !error && !data,
    data,
    error,
  };
}

export default useApi;
```

**Comment by aje** [comment]
> @thiagoconnectcom Something like this:
> 
> ```js
> import useSWR from 'swr';
> 
> /**
>  * Re-usable SWR api implementation.
>  *
>  * @param {string} url
>  * @param {object} params
>  * @returns object
>  */
> function useApi(url, params) {
>   const usp = new URLSearchParams(params);
> 
>   // Create a stable key for SWR
>   usp.sort();
>   const qs = usp.toString();
> 
>   const { data, error } = useSWR(`${url}?${qs}`);
> 
>   return {
>     loading: !error && !data,
>     data,
>     error,
>   };
> }
> 
> export default useApi;
> ```


This creates a key each time user uses another query, I'm looking for something that can change the query but not the key so it won't delete the cache

**Comment by welschmoor** [comment]
Noone?
I need to preserve cache when the query params change

**Comment by jeff-kilbride** [comment]
@aje 
@welschmoor 

I don't understand the problem you're having. The SWR cache is similar to a Javascript Map object. So, each URL acts as a key and stores it's own information in the cache. When you change keys, you are not "deleting" the cache. You are adding another key to the cache with its own data.

If you want something that never  changes, take a look at the useSWRImmutable hook.

**Comment by welschmoor** [comment]
> @aje @welschmoor
> 
> I don't understand the problem you're having. The SWR cache is similar to a Javascript Map object. So, each URL acts as a key and stores it's own information in the cache. When you change keys, you are not "deleting" the cache. You are adding another key to the cache with its own data.
> 
> If you want something that never changes, take a look at the useSWRImmutable hook.

Sure, it does not delete the cache, it simply no longer shows stale data while it is being revalidated, so you see a blank page when the query params change. I posted the solution above to how to avoid data disappearing from screen when changing the url.

**Comment by gr8karma** [comment]
> Sure, it does not delete the cache, it simply no longer shows stale data while it is being revalidated, because it thinks it's a completely new call, so you see a blank page when the query params change. I posted the solution above to how to avoid data from disappearing from screen when changing the url query params.

The `keepPreviousData` option doesn't work for you?

https://swr.vercel.app/docs/advanced/understanding#return-previous-data-for-better-ux

**Comment by gr8karma** [comment]
> Sure, it does not delete the cache, it simply no longer shows stale data while it is being revalidated, because it thinks it's a completely new call, so you see a blank page when the query params change. I posted the solution above to how to avoid data from disappearing from screen when changing the url query params.

The `keepPreviousData` option doesn't work for you?

https://swr.vercel.app/docs/advanced/understanding#return-previous-data-for-better-ux

**Comment by welschmoor** [comment]
> > Sure, it does not delete the cache, it simply no longer shows stale data while it is being revalidated, because it thinks it's a completely new call, so you see a blank page when the query params change. I posted the solution above to how to avoid data from disappearing from screen when changing the url query params.
> 
> The `keepPreviousData` option doesn't work for you?
> 
> https://swr.vercel.app/docs/advanced/understanding#return-previous-data-for-better-ux

nice! I've never heard of it

**Comment by 3pleFly** [comment]
I faced this issue two years afo when i was starting to use swr. But then i just did

If(data)

I wonder what stops you from doing that?
