### ISSUE TITLE
Default local state data that comes from an API is undefined

### ISSUE THREAD

**Issue by jericopulvera** [zeit/swr#378]
I have an edit user page that gets the data from an API via SWR and I want its data to be the default data in my local state hook. 

The problem seems to be that the state gets initialized first before the SWR returns the data thus the default becoming undefined. 

I would like to know the right approach to make this work.

https://codesandbox.io/s/fervent-jackson-v4czz?file=/pages/index.js

Thank you! 🙏

**Comment by huozhi** [comment]
@jericopulvera consider using the `initialData` option?

```js
const { data: user } = useSwr(
  "your url", 
  fetcher,
  {
    initialData: {}
  }
);
```

**Comment by jericopulvera** [comment]
> @jericopulvera consider using the `initialData` option?
> 
> ```js
> const { data: user } = useSwr(
>   "your url", 
>   fetcher,
>   {
>     initialData: {}
>   }
> );
> ```

Sorry but it's not what I'm looking for. 

I want the initial data of my state hook to be from the API. 

Maybe I could use this if I'm working using SSR but right now I'm using it on CSR.

**Comment by huozhi** [comment]
did you mean you'd like to wait until first fetched response and use it as initial data for default value of useState? like Suspense?

**Comment by jericopulvera** [comment]
> did you mean you'd like to wait until first fetched response and use it as initial data for default value of useState? like Suspense?

Yes. Is this possible without using Suspense?

**Comment by sergiodxa** [comment]
You will need to have a component to fetch the date, and once data stop being undefined render a component psssing that data, this sub component will have your state initialized with the prop value.

Another option is to use SWR as you state directly, you can use mutate to update the cache data while the user edit it, mutate supports a third argument to disable revalidation passing false, something like `mutate(key, newData, false)`

**Comment by jericopulvera** [comment]
> You will need to have a component to fetch the date, and once data stop being undefined render a component psssing that data, this sub component will have your state initialized with the prop value.
> 
> Another option is to use SWR as you state directly, you can use mutate to update the cache data while the user edit it, mutate supports a third argument to disable revalidation passing false, something like `mutate(key, newData, false)`

will there be a performance issue on option 2? compared to using state?

**Comment by sergiodxa** [comment]
Nope, I do it for a really long form without issues.
