### ISSUE TITLE
rel="preload" or "prefetch"?

### ISSUE THREAD

**Issue by heymartinadams** [zeit/swr#382]
In your docs for SWR you mention `<link rel="preload">` ([here](https://github.com/zeit/swr#prefetching-data)), yet NextJS Link recommends `prefetch` ([here](https://nextjs.org/docs/api-reference/next/link)). Which one is it?

**Comment by sergiodxa** [comment]
Prefetch (using the `link` tag) is used to fetch resources used in the next page navigation (in the normal browser meaning of page navigation (aka a full page reload).

Preload is used to load data intended to be used in the same page you currently are, so in this case is the best option.

Next.js Link component call prefetch to the prop, but internally it uses a `<link rel="preload">` tag.

You can read more about prefetch vs preload in the link tag here https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Other_resource_preloading_mechanisms.

**Comment by shuding** [comment]
Exactly! `<Link prefetch>` is a Next.js specific thing, where “Link” means literally a URL link. `<link rel="preload">` is something in the HTML standard and used for preloading resources.
