### ISSUE TITLE
 Bound Mutate breaks the cache and mutate abnormal behaviour

### ISSUE THREAD

**Issue by sainhimanshu9** [zeit/swr#383]
I've used bound mutate and it is breaking the cache as soon as handle change runs, i want to change a role_id of the tableData. 
**In other file i've used mutate of swr exactly like here(without key) and it was perfectly fine** but here neither the bound mutate is working nor swr's one. swr's mutate doing no action at all while bound mutate breaks the cache, suddenly whole data collapses.
 
**It must be a bug that mutate from swr is running sometimes without key while bound mutate breaks the cache.**

```
const { data, error, mutate } = useSWR(url);
  const { data: swrData } = data || {};
  const { stats_data,  lead_data: tableData = [] } =
    swrData || {};

const handleChange = (event, id) => {
    event.persist();
      mutate(
        (tableData.find((item) => item.id === id).role_id =
          event.target.value),
          false
      );
  };
````

**Comment by sergiodxa** [comment]
From what I used in the snippet you shared, you ara changing the cached value with the first element of tableData found using the find.

That is most likely changing it to an unexpected shape and breaking your app. Try creating a new copy of the whole cached data with the updated value.

**Comment by sainhimanshu9** [comment]
this works when i dont have checks, what about those cases when i'm having certain checks?
like this:
```
const { data } = useSWR(url);
const { data: usersData } = data || {};
const { data: roles } = useSWR(`${url}/roles`);
const { data: rolesData } = roles || {};
const { user_roles } = rolesData || {};
const handleChange = async (value, id, type) => {
    
          if (type === "user") {
            const tempData = _cloneDeep(data.data);
             tempData.find((item) => item.id === id).role_id = value;
            mutate(url, { ...data, data: tempData }, false);
          }
   } 
//here show the select only if role_id of particular user exists in id of user_roles
usersData.map(user=>
    <div>
    {user_roles &&
    user_roles.find(
      (item) => item.id === user.role_id
    ) ? (
      <TextField
       
        size="small"
        name="option"
        onChange={(e) => {
        
          handleChange(e.target.value, user.id, "user");
        }}
        select
        
        value={
          (user_roles.find(
            (item) => item.id === user.role_id
          ) &&
            user.role_id) ||
          ""
        }
       
      >
        <option value="" disabled>
          Select User Role
        </option>
        {user_roles.map(
            (option, index) => (
              <option
                key={`user-role-${index}`}
                value={option.id}
              >
                {option.name || "-"}
              </option>
            )
          )}
      </TextField>
    ) : (
      "-"
    )}</div>)

```
in the above case even when value is among the user_roles id, after mutate, rather than changing the value of select, select component doesn't render and **-**  renders, even when the id which i mutate is satisfying the checks.
why is it happening?

**Comment by sergiodxa** [comment]
Could you create a CodeSandbox to replicate it? I could check it there

**Comment by sainhimanshu9** [comment]
@sergiodxa  here, https://codesandbox.io/s/winter-sea-6dxrp?file=/src/User.js

api wont run but i've written the api response and all the swr related data are commented. still have a look.
