### ISSUE TITLE
Enabling Suspense hangs browser

### ISSUE THREAD

**Issue by fnky** [zeit/swr#39]
I have tried to setup an example project using the SWR hook with GraphQL, as explained in the documentation. However, enabling suspense in the options of `useSWR` causes the browser to hang.

I have an [example project on CodeSandbox](https://codesandbox.io/s/swr-movies-example-zgunu) which shows this. Simply go to either `screens/movies.tsx` or `screens/movie-details.tsx` and uncomment the line with the `// { suspense: true }`.

**Comment by adwd** [comment]
I have same problem but without GraphQL. Minimum app for reproduction is here => https://codesandbox.io/s/react-suspense-with-zeitswr-r5z2k

**Comment by Nyura95** [comment]
Me too. Just a bug with this feature I think 

To reproduce, copy/paste the code below:

<img width="564" alt="Capture d’écran 2019-10-30 à 12 56 15" src="https://user-images.githubusercontent.com/10028203/67856373-ae146280-fb14-11e9-8672-f0913ffc136f.png">

getMessages runs a loop each time and Suspense rests in fallback

**Comment by erikjung** [comment]
Looks like a duplicate of #46

**Comment by fnky** [comment]
Closing this issue as it seems to be resolved in #49 — there were a "Close" keyword, but it wasn't separated for each issue, so it only closed the first issue regarding this.
