### ISSUE TITLE
Long time between data appearing and real data loading useSWRpages

### ISSUE THREAD

**Issue by rafinskipg** [zeit/swr#398]
Hello, this is the case, i need some guidance because maybe I am doing something wrong.

I am using useSWRPages. And I know my code is fine ( I have seen it working perfectly before) 

But now, when the items load on the client side, they appear repeated. Until, after a couple of seconds the client side kicks in and loads the real data. Is like a cache was giving me some data. But it takes a long time and is quite noticeable. 

My page is serverside rendered, and the "initialData" passed to the useSWRPages come from the server properties. (This may affect)  (?) 

Any clue on what could be wrong? 

````javascript
const {
    pages,
    isLoadingMore,
    loadMore,
    isEmpty,
    isReachingEnd,
  } = useSWRPages(
    identificator,
    ({ offset, withSWR }) => {
      const apiUrl = `${API.content[props.type.slug]}?limit=10${
        offset ? '&from=' + offset : ''
      }${query ? `&${query}` : ''}`
      const { data } = withSWR(
        useSWR(apiUrl, fetch, { initialData: props.initialData })
      )

      if (!data) return <LoadingItems />

      const { results = [] } = data
      return results.map((item) => {
        return (
          <div key={item.id + item.createdAt} >
            The item
          </div>
        )
      })
    },
    (SWR) => {
      // Calculates the next page offset
      const nextOffset = SWR.data && SWR.data.results && SWR.data.results.length >= 10
        ? (SWR.data.from * 1) + (SWR.data.limit * 1)
        : null
        return nextOffset
    },
    []
  )

````

**Comment by rafinskipg** [comment]
It seems like its giving me the same offset all the time, I don't understand why. When I change tabs and come to the same tab, the client side "whatever" do a revalidation and the offsets and content load correctly

**Comment by sergiodxa** [comment]
Most probably is the initial data, related to https://github.com/zeit/swr/issues/284, try only sending the initial data in the first request.

**Comment by rafinskipg** [comment]
yeah that's right @sergiodxa , it works this way. Should we expect any change of behavior in the future?

```javascript
const { data } = withSWR(
        useSWR(apiUrl, fetch, !offset ? { initialData:  props.initialData} : null)
      )
```
