### ISSUE TITLE
Using GraphQL doesn't always revalidate

### ISSUE THREAD

**Issue by fnky** [zeit/swr#40]
There's a problem with revalidating data in some circumstances which can be seen in [this example project](https://codesandbox.io/s/swr-movies-example-zgunu). This is based on the 

1. Navigate to a details page by clicking on one of the items.
2. See the data load, and correctly show.
3. Go back to the previous page.
4. Click on another item.
5. See that it sometimes doesn't revalidate/update the state for the given page.

Note that the project uses `@reach/router` which provides a param `slug` through the `MovieDetailsScreen` component, as it is a route component.

My theory is that the revalidation doesn't happen because the "key" (GraphQL) is always the same even though the provided variable changes and therefore doesn't revalidate, but I don't know exactly the inner workings of `useSWR` with regards to GraphQL.

**Comment by sergiodxa** [comment]
From what I read in the library code there is nothing special. They literally use the key as an identified, what you could do is to use the trigger function the module export to force a revalidación even if the query hasn’t changed, another option is to don’t use GraphQL variable and instead use template literals to interpolate the variable in the query

**Comment by fnky** [comment]
> From what I read in the library code there is nothing special

My understanding is that the passed url/GraphQL in the first argument is used as the a key in the cache, which makes sense to use, if that key changes.

> what you could do is to use the trigger function the module export to force a revalidación even if the query hasn’t changed

That is one way, but requires one to manage when revalidation should happen for different resources, which is suboptimal.

> another option is to don’t use GraphQL variable and instead use template literals to interpolate the variable in the query

I want to use GraphQL variables, because otherwise you'll have to generate a new query each time making it harder to reuse. Variables are useful because you don't have to create different queries for each small change, e.g. passing variables to the arguments of a query.

Consider this:

```
const getPersonByIdQuery = (id) => `
  query {
    person(id: ${id}) {
      id
    }
  }
`

const getPersonByNameQuery = (name) => `
  query {
    person(name: ${name}) {
      id
    }
  }
`
```

Versus this:

const personQuery = `
  query Person(id: ID, name: String) {
    person(id: $id, name: $name) {
      id
    }
  }
`
```

This makes creating queries overly complicated with more sophisticated APIs, e.g. with filtering, ordering, pagination, etc. Not ideal in the long term.

As previously mentioned in the original post, it would be nice to be able to provide your own key/key extractor function to `useSWR` that allows you to define what the key should be for the particular resource in cache, that way, you'll have move control without having to use strange hacks around it.

**Comment by quietshu** [comment]
We're working on a solution for this in https://github.com/zeit/swr/pull/37 , so you'll be able to claim dependencies of `fn` (in your example it should be `variables`).

**Comment by fnky** [comment]
@quietshu Nice, this is probably better than my solution :)
