### ISSUE TITLE
`revalidateOnMount` does not exist

### ISSUE THREAD

**Issue by grikomsn** [zeit/swr#405]
Currently working on Next.js with TypeScript on Visual Studio Code, apparently `revalidateOnMount` does not exist. Below are screenshots of vscode intellisense and error message:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/8220954/82416580-76670b00-9aa4-11ea-8ad1-96439ccc0bd7.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/8220954/82416600-7e26af80-9aa4-11ea-9e2d-ccf419df66e3.png">

**Comment by sergiodxa** [comment]
It was not released yet to npm

**Comment by grikomsn** [comment]
Thank you for the response! Any timeline info on when `revalidateOnMount` will be available?

**Comment by sergiodxa** [comment]
If someone knows that is @shuding

**Comment by shuding** [comment]
Hi @grikomsn @sergiodxa I just released swr@0.2.1, and it should be included!

**Comment by grikomsn** [comment]
Thank you for the release! ✨
