### ISSUE TITLE
Which browsers are supported?

### ISSUE THREAD

**Issue by irekrog** [zeit/swr#407]

**Comment by huozhi** [comment]
@irekrog it depends on how you compiling your code on application side. by default swr is compiled to es5 by typescript. and didn't rely on any browser specific features. basically browsers supported es5, Map, react can work with swr without doubt.

if you want to support more browsers, you can use `@babel/preset-env` with browserslist config to cover your targeting browsers https://babeljs.io/docs/en/babel-preset-env#browserslist-integration

**Comment by irekrog** [comment]
@huozhi thanks
