### ISSUE TITLE
Refresh Browser deletes Cache

### ISSUE THREAD

**Issue by timhilgenstoehler** [zeit/swr#409]
Hey, really great repository! I am super happy with how its working but Is it possible that the generated cached api data will be persistent even if I refresh the browser?

**Comment by sergiodxa** [comment]
That's expected, the cache is only stored in-memory, if you want to persist it you can subscribe to changes in the cache and sync back to localStorage, then before rendering the app read from populate the cache from the localStorage data.

I have a small libraries you can use for that https://github.com/sergiodxa/swr-sync-storage, it will sync every cache key to a key in localStorage or sessionStorage, the code is really small in case you want to implement it yourself https://github.com/sergiodxa/swr-sync-storage/blob/master/src/index.ts.

**Comment by timhilgenstoehler** [comment]
Thats sounds great! Do you maybe have a working example for this package in use?

**Comment by sergiodxa** [comment]
I have only used in internal apps at my work, I have not public example usages.

The way to use it is to import `syncWithStorage` function and call it before you render you app, in Next.js that it in _app.js, outside the component and checking you are running client-side.

**Comment by timhilgenstoehler** [comment]
Jeah thanks, i got ist working. Exactly what i wanted :)
