### ISSUE TITLE
Performance discussion

### ISSUE THREAD

**Issue by baoduy** [zeit/swr#43]
Hi, This is an interesting hooks. However, keep re-validating the state by calling the Server API may casing the performance issues if there are many concurrent users. How could we handle this issue? shall we combine this with Redux? 

Thanks and Regards
Duy

**Comment by sergiodxa** [comment]
By default `refreshInterval` is disabled (it doesn't do polling, it only refresh when you run `mutate`, `trigger` or your tab is focused again.

**Comment by quietshu** [comment]
Also focus revalidation can be disabled too 👍

**Comment by baoduy** [comment]
Thank you so much for your replay. This is really a potential component to replace Redux and simplify the development as well.

Thanks 
Duy
