### ISSUE TITLE
For fun: JetSet

### ISSUE THREAD

**Issue by glortho** [zeit/swr#47]
SWR is awesome! In a previous chapter of my career our team undertook a similar project at one point (pre-hooks, using HOCs) -- https://github.com/DigitalGlobe/jetset -- but didn't land on nearly the level of sophistication and elegance you have achieved here. Huge props to you and the team! 💪

**Comment by pacocoursey** [comment]
JetSet looks really great! Can definitely see a lot of scope overlap. I will say I'm thankful for React Hooks, I think it's made libraries like this a lot easier to use.

Thanks for sharing 😄
