### ISSUE TITLE
Conditional fetching

### ISSUE THREAD

**Issue by bywo** [zeit/swr#50]
Hey, thanks for putting together this library.

I'm curious how you think about conditional fetching since we can't use conditionals with React hooks. For example, say we have a storefront with a list of items. And if the current user has special access, each item will get augmented with a discount.

In totally invalid React pseudocode:
```
const {data: user} = userSWR(`/api/me`)
const {data: items} = useSWR(`/api/items`)

let discounts = []
if (user.isSpecial) {
  const {data} = useSWR(`/api/discounts`)
  if (data) { discounts = data }
}

return <ItemList items={items} discounts={discounts} />
```

Being able to pass `fetch` in gives us an escape hatch, but I'm not sure if that's how you intended it to be used.
```
const {data: user} = userSWR(`/api/me`)
const {data: items} = useSWR(`/api/items`)
const {data: discounts} = useSWR(`/api/discounts`, (query) => {
  if (user.isSpecial) {
    return fetch(query)
  } else {
    return []
  }
});

return <ItemList items={items} discounts={discounts} />
```

How would you go about implementing this pattern? Thanks!

**Comment by quietshu** [comment]
@bywo yep there is a way to do that very easily: just use `null` as the key so it won't fetch.

For example:
```
jsconst {data: user} = userSWR(`/api/me`)
const {data: items} = useSWR(`/api/items`)

let discounts = []
const {data} = useSWR(user.isSpecial ? `/api/discounts` : null)
if (data) { discounts = data }

return <ItemList items={items} discounts={discounts} />
```

**Comment by bywo** [comment]
Sweet. Thanks for the quick reply!

**Comment by daviddossantos** [comment]
hello guys, I did the documentation, putting null return, but still looking for something in the api infinitely, has anyone had this problem?

![image](https://user-images.githubusercontent.com/37313667/101166076-741a6780-3616-11eb-89b5-bea0630a24c8.png)

**Comment by daviddossantos** [comment]
I did it the same way but my `data` remains` undefined` forever

**Comment by daviddossantos** [comment]
someone had this problem, can give a light
