### ISSUE TITLE
Cache issue - can't get new data with either `trigger` or `revalidate`

### ISSUE THREAD

**Issue by csterritt** [zeit/swr#60]
Really like the idea of useSWR, really wish I could get it to work :-(

Here's what I'm doing:

~~~
    const { data: userId, error: userIdError } = useSWR(
        `/user-id/${authenticateMachine.userName}`,
        () => theThingStore.getUserId(authenticateMachine.userName)
    )
    const { data: things, error: thingsError } = useSWR(
        `/things/${userId}`,
        () => theThingStore.getCurrentThingsFromDb(userId)
    )

    const doAddNewThing = () => {
        const myInit = {
            body: {
                userTitle: `Thing ${new Date().toJSON()
                    .substr(11, 8)
                    .split(':')
                    .join('-')}`,
            },
            headers: {
                'Content-Type': 'application/json',
            },
        }

        return API.post(API_NAME, `/add-new-thing`, myInit)
            .then((data) => {
                console.log('add-new-thing returned', data)
                setTimeout(() => {
                    console.log('Doing trigger to get new content.')
                    trigger(`/things`)
                }, 2000)
            })
            .catch((err) => {
                console.log('add-new-thing failed with error', err)
            })
    }

    // react code to display the things list.
~~~

For the `trigger` call, I've tried:

~~~
    trigger('/things')
    trigger(`/things/${userId}`)
~~~

I've also tried `revalidate` instead of `trigger`.

I thought that would cause a re-fetch of my data, and show me the new data.  However,
it does not call my `getCurrentThingsFromDb` method after the `trigger` runs.
My list of items remains the ones before the add.

In fact, if I reload the page, it keeps the old data!

I've got a "run a `curl` every half-second" process running next to the browser, and
it sees the number of things increase, so I know that the API is returning the right
data; after the `API.post`, and before the `trigger`, there's new data arriving at
my machine.

I originally wasn't using the `setTimeout`; longer timeouts don't help.

Thanks!

**Comment by sergiodxa** [comment]
You are fetching /things/id and then you trigger against /things instead of /things/id.

Now if you reload the page and still got the old data it’s not an issue with useSWR since the libs its not caching between reloads, I think your API it’s not updating the data accordingly.

**Comment by csterritt** [comment]
> You are fetching /things/id and then you trigger against /things instead of /things/id.

Sorry, I guess I didn't explain very well that I tried (separately) triggering against both '/things' and '/things/id'.  Neither worked.

It is now working for a (delayed) trigger, by changing what the API returned... not sure why that helps, I'll keep working on it.

To avoid having to do the delay, I'm trying `mutate` and running into different errors.  I'll try to fix them myself, and post if I fail.

Thanks for the help!

**Comment by csterritt** [comment]
And it works with `mutate`!  I had the second argument to `mutate` wrong, so it flamed out spectacularly with a "Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement." statement.

Thanks again!
