### ISSUE TITLE
BUG: Infinite loop with suspense on rejected promise

### ISSUE THREAD

**Issue by KatSick** [zeit/swr#66]
See: https://codesandbox.io/s/swr-playground-zloyr

Steps to reproduce:
- Use SWR
- Set suspense to true
- Set shouldRetryOnError to false
- Reject HTTP request (or just promise)

Actual result:
Endless loop of retrying

Expected result:
Error boundary should catch error'ed promise

**Comment by quietshu** [comment]
Thanks for reporting!

**Comment by JustInToCoding** [comment]
Still hapening for me on version "^0.1.7". I'm using the SWRConfig to set suspense to true. It seems to also ignore these settings:
`errorRetryInterval: 100000,
shouldRetryOnError: false`
If I put suspense to false, it won't infinitely retry.

**Comment by quietshu** [comment]
@JustInToCoding sorry! The fix should be included in the latest version `0.1.8`. Here's a working example: https://codesandbox.io/s/swr-suspense-mckdf
