### ISSUE TITLE
Interval polling on React Native

### ISSUE THREAD

**Issue by aarshaw** [zeit/swr#75]
Currently on React Native, the API will fetch the data on initial load but won't poll for updates like it does on web.

**Comment by quietshu** [comment]
On React Native there’s no onfocus revalidation implementation. You can use the `refreshInterval` option to do polling for now.

**Comment by outaTiME** [comment]
yup, but AppState could be used when app comes to foreground ✌️ 

https://reactnative.dev/docs/appstate

**Comment by shuding** [comment]
@outaTiME Good point! Would you mind opening an issue for it?

**Comment by outaTiME** [comment]
yup, i create that one:

https://github.com/vercel/swr/issues/417
