### ISSUE TITLE
Using query params

### ISSUE THREAD

**Issue by polc** [zeit/swr#78]
Hi there, 

Thanks for this little library ! After exploring the doc I could not find a way to invalidate multiple entries at once. For example, if I've a search bar `/projects?description=My Search`, when adding a new project I would like to invalidate all `/projects/*`.

Any idea how this could be implemented?

**Comment by quietshu** [comment]
We've planned to add cache APIs and inactive cache collection. Scenarios like this will be supported soon!

**Comment by sergiodxa** [comment]
I think this could now be solved with the exposed cache, get all cache keys, filter based on `/projects/*` glob and then call mutate against it without data to revalidate it or call cache.delete to delete them altogether

**Comment by polc** [comment]
Looks good, thanks!
