### ISSUE TITLE
Dependent fetching on list of urls

### ISSUE THREAD

**Issue by waptik** [zeit/swr#97]
First of all, thanks 👍  for this awesome library. Heard about it on zeit's twiiter page this week and i wanted to try my hands on it.

This issue is related to #71 . In my case, i'll like to get info of each pokemon for each pokemon's url from the [api](https://pokeapi.co/api/v2/pokemon), instead of displaying info based on a clicked pokemon.
I'm using the pokemon api as an example. demo is ➡️  [codesandbox](https://codesandbox.io/s/jovial-aryabhata-787t0)

**Comment by quietshu** [comment]
Hi @waptik !

React doesn't allow people to use dynamic number of Hooks inside a component. But you can move each pokemon into their own component and fetch via SWR inside. I forked your demo: https://codesandbox.io/s/happy-bhaskara-vgsf7

**Comment by waptik** [comment]
Thanks it works. I forgot that breaking things into components makes life easier.
